
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package rainbow_metal.init;

import rainbow_metal.RainbowMetalMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class RainbowMetalModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, RainbowMetalMod.MODID);
	public static final RegistryObject<Item> BLUE_200_PLATE = block(RainbowMetalModBlocks.BLUE_200_PLATE);
	public static final RegistryObject<Item> BLUE_300_PLATE = block(RainbowMetalModBlocks.BLUE_300_PLATE);
	public static final RegistryObject<Item> BLUE_400_PLATE = block(RainbowMetalModBlocks.BLUE_400_PLATE);
	public static final RegistryObject<Item> BLUE_500_PLATE = block(RainbowMetalModBlocks.BLUE_500_PLATE);
	public static final RegistryObject<Item> BLUE_600_PLATE = block(RainbowMetalModBlocks.BLUE_600_PLATE);
	public static final RegistryObject<Item> BLUE_700_PLATE = block(RainbowMetalModBlocks.BLUE_700_PLATE);
	public static final RegistryObject<Item> BLUE_800_PLATE = block(RainbowMetalModBlocks.BLUE_800_PLATE);
	public static final RegistryObject<Item> BLUE_900_PLATE = block(RainbowMetalModBlocks.BLUE_900_PLATE);
	public static final RegistryObject<Item> BROWN_50_PLATE = block(RainbowMetalModBlocks.BROWN_50_PLATE);
	public static final RegistryObject<Item> BROWN_100_PLATE = block(RainbowMetalModBlocks.BROWN_100_PLATE);
	public static final RegistryObject<Item> BROWN_200_PLATE = block(RainbowMetalModBlocks.BROWN_200_PLATE);
	public static final RegistryObject<Item> BROWN_300_PLATE = block(RainbowMetalModBlocks.BROWN_300_PLATE);
	public static final RegistryObject<Item> BROWN_400_PLATE = block(RainbowMetalModBlocks.BROWN_400_PLATE);
	public static final RegistryObject<Item> BROWN_500_PLATE = block(RainbowMetalModBlocks.BROWN_500_PLATE);
	public static final RegistryObject<Item> BROWN_600_PLATE = block(RainbowMetalModBlocks.BROWN_600_PLATE);
	public static final RegistryObject<Item> BROWN_700_PLATE = block(RainbowMetalModBlocks.BROWN_700_PLATE);
	public static final RegistryObject<Item> BROWN_800_PLATE = block(RainbowMetalModBlocks.BROWN_800_PLATE);
	public static final RegistryObject<Item> BROWN_900_PLATE = block(RainbowMetalModBlocks.BROWN_900_PLATE);
	public static final RegistryObject<Item> CYAN_50_PLATE = block(RainbowMetalModBlocks.CYAN_50_PLATE);
	public static final RegistryObject<Item> CYAN_100_PLATE = block(RainbowMetalModBlocks.CYAN_100_PLATE);
	public static final RegistryObject<Item> CYAN_200_PLATE = block(RainbowMetalModBlocks.CYAN_200_PLATE);
	public static final RegistryObject<Item> CYAN_300_PLATE = block(RainbowMetalModBlocks.CYAN_300_PLATE);
	public static final RegistryObject<Item> CYAN_400_PLATE = block(RainbowMetalModBlocks.CYAN_400_PLATE);
	public static final RegistryObject<Item> CYAN_500_PLATE = block(RainbowMetalModBlocks.CYAN_500_PLATE);
	public static final RegistryObject<Item> CYAN_600_PLATE = block(RainbowMetalModBlocks.CYAN_600_PLATE);
	public static final RegistryObject<Item> CYAN_700_PLATE = block(RainbowMetalModBlocks.CYAN_700_PLATE);
	public static final RegistryObject<Item> CYAN_800_PLATE = block(RainbowMetalModBlocks.CYAN_800_PLATE);
	public static final RegistryObject<Item> CYAN_900_PLATE = block(RainbowMetalModBlocks.CYAN_900_PLATE);
	public static final RegistryObject<Item> GRAY_50_PLATE = block(RainbowMetalModBlocks.GRAY_50_PLATE);
	public static final RegistryObject<Item> GRAY_100_PLATE = block(RainbowMetalModBlocks.GRAY_100_PLATE);
	public static final RegistryObject<Item> GRAY_200_PLATE = block(RainbowMetalModBlocks.GRAY_200_PLATE);
	public static final RegistryObject<Item> GRAY_300_PLATE = block(RainbowMetalModBlocks.GRAY_300_PLATE);
	public static final RegistryObject<Item> GRAY_400_PLATE = block(RainbowMetalModBlocks.GRAY_400_PLATE);
	public static final RegistryObject<Item> GRAY_500_PLATE = block(RainbowMetalModBlocks.GRAY_500_PLATE);
	public static final RegistryObject<Item> GRAY_600_PLATE = block(RainbowMetalModBlocks.GRAY_600_PLATE);
	public static final RegistryObject<Item> GRAY_700_PLATE = block(RainbowMetalModBlocks.GRAY_700_PLATE);
	public static final RegistryObject<Item> GRAY_800_PLATE = block(RainbowMetalModBlocks.GRAY_800_PLATE);
	public static final RegistryObject<Item> GRAY_900_PLATE = block(RainbowMetalModBlocks.GRAY_900_PLATE);
	public static final RegistryObject<Item> GREEN_50_PLATE = block(RainbowMetalModBlocks.GREEN_50_PLATE);
	public static final RegistryObject<Item> GREEN_100_PLATE = block(RainbowMetalModBlocks.GREEN_100_PLATE);
	public static final RegistryObject<Item> GREEN_200_PLATE = block(RainbowMetalModBlocks.GREEN_200_PLATE);
	public static final RegistryObject<Item> GREEN_300_PLATE = block(RainbowMetalModBlocks.GREEN_300_PLATE);
	public static final RegistryObject<Item> GREEN_400_PLATE = block(RainbowMetalModBlocks.GREEN_400_PLATE);
	public static final RegistryObject<Item> GREEN_500_PLATE = block(RainbowMetalModBlocks.GREEN_500_PLATE);
	public static final RegistryObject<Item> GREEN_600_PLATE = block(RainbowMetalModBlocks.GREEN_600_PLATE);
	public static final RegistryObject<Item> GREEN_700_PLATE = block(RainbowMetalModBlocks.GREEN_700_PLATE);
	public static final RegistryObject<Item> GREEN_800_PLATE = block(RainbowMetalModBlocks.GREEN_800_PLATE);
	public static final RegistryObject<Item> GREEN_900_PLATE = block(RainbowMetalModBlocks.GREEN_900_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_50_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_50_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_100_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_100_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_200_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_200_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_300_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_300_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_400_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_400_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_500_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_500_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_600_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_600_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_700_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_700_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_800_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_800_PLATE);
	public static final RegistryObject<Item> LIGHT_BLUE_900_PLATE = block(RainbowMetalModBlocks.LIGHT_BLUE_900_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_50_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_50_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_100_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_100_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_200_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_200_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_300_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_300_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_400_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_400_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_500_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_500_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_600_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_600_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_700_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_700_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_800_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_800_PLATE);
	public static final RegistryObject<Item> LIGHT_GRAY_900_PLATE = block(RainbowMetalModBlocks.LIGHT_GRAY_900_PLATE);
	public static final RegistryObject<Item> LIME_50_PLATE = block(RainbowMetalModBlocks.LIME_50_PLATE);
	public static final RegistryObject<Item> LIME_100_PLATE = block(RainbowMetalModBlocks.LIME_100_PLATE);
	public static final RegistryObject<Item> LIME_200_PLATE = block(RainbowMetalModBlocks.LIME_200_PLATE);
	public static final RegistryObject<Item> LIME_300_PLATE = block(RainbowMetalModBlocks.LIME_300_PLATE);
	public static final RegistryObject<Item> LIME_400_PLATE = block(RainbowMetalModBlocks.LIME_400_PLATE);
	public static final RegistryObject<Item> LIME_500_PLATE = block(RainbowMetalModBlocks.LIME_500_PLATE);
	public static final RegistryObject<Item> LIME_600_PLATE = block(RainbowMetalModBlocks.LIME_600_PLATE);
	public static final RegistryObject<Item> LIME_700_PLATE = block(RainbowMetalModBlocks.LIME_700_PLATE);
	public static final RegistryObject<Item> LIME_800_PLATE = block(RainbowMetalModBlocks.LIME_800_PLATE);
	public static final RegistryObject<Item> LIME_900_PLATE = block(RainbowMetalModBlocks.LIME_900_PLATE);
	public static final RegistryObject<Item> MAGENTA_50_PLATE = block(RainbowMetalModBlocks.MAGENTA_50_PLATE);
	public static final RegistryObject<Item> MAGENTA_100_PLATE = block(RainbowMetalModBlocks.MAGENTA_100_PLATE);
	public static final RegistryObject<Item> MAGENTA_200_PLATE = block(RainbowMetalModBlocks.MAGENTA_200_PLATE);
	public static final RegistryObject<Item> MAGENTA_300_PLATE = block(RainbowMetalModBlocks.MAGENTA_300_PLATE);
	public static final RegistryObject<Item> MAGENTA_400_PLATE = block(RainbowMetalModBlocks.MAGENTA_400_PLATE);
	public static final RegistryObject<Item> MAGENTA_500_PLATE = block(RainbowMetalModBlocks.MAGENTA_500_PLATE);
	public static final RegistryObject<Item> MAGENTA_600_PLATE = block(RainbowMetalModBlocks.MAGENTA_600_PLATE);
	public static final RegistryObject<Item> MAGENTA_700_PLATE = block(RainbowMetalModBlocks.MAGENTA_700_PLATE);
	public static final RegistryObject<Item> MAGENTA_800_PLATE = block(RainbowMetalModBlocks.MAGENTA_800_PLATE);
	public static final RegistryObject<Item> MAGENTA_900_PLATE = block(RainbowMetalModBlocks.MAGENTA_900_PLATE);
	public static final RegistryObject<Item> ORANGE_50_PLATE = block(RainbowMetalModBlocks.ORANGE_50_PLATE);
	public static final RegistryObject<Item> ORANGE_100_PLATE = block(RainbowMetalModBlocks.ORANGE_100_PLATE);
	public static final RegistryObject<Item> ORANGE_200_PLATE = block(RainbowMetalModBlocks.ORANGE_200_PLATE);
	public static final RegistryObject<Item> ORANGE_300_PLATE = block(RainbowMetalModBlocks.ORANGE_300_PLATE);
	public static final RegistryObject<Item> ORANGE_400_PLATE = block(RainbowMetalModBlocks.ORANGE_400_PLATE);
	public static final RegistryObject<Item> ORANGE_500_PLATE = block(RainbowMetalModBlocks.ORANGE_500_PLATE);
	public static final RegistryObject<Item> ORANGE_600_PLATE = block(RainbowMetalModBlocks.ORANGE_600_PLATE);
	public static final RegistryObject<Item> ORANGE_700_PLATE = block(RainbowMetalModBlocks.ORANGE_700_PLATE);
	public static final RegistryObject<Item> ORANGE_800_PLATE = block(RainbowMetalModBlocks.ORANGE_800_PLATE);
	public static final RegistryObject<Item> ORANGE_900_PLATE = block(RainbowMetalModBlocks.ORANGE_900_PLATE);
	public static final RegistryObject<Item> PINK_50_PLATE = block(RainbowMetalModBlocks.PINK_50_PLATE);
	public static final RegistryObject<Item> PINK_100_PLATE = block(RainbowMetalModBlocks.PINK_100_PLATE);
	public static final RegistryObject<Item> PINK_200_PLATE = block(RainbowMetalModBlocks.PINK_200_PLATE);
	public static final RegistryObject<Item> PINK_300_PLATE = block(RainbowMetalModBlocks.PINK_300_PLATE);
	public static final RegistryObject<Item> PINK_400_PLATE = block(RainbowMetalModBlocks.PINK_400_PLATE);
	public static final RegistryObject<Item> PINK_500_PLATE = block(RainbowMetalModBlocks.PINK_500_PLATE);
	public static final RegistryObject<Item> PINK_600_PLATE = block(RainbowMetalModBlocks.PINK_600_PLATE);
	public static final RegistryObject<Item> PINK_700_PLATE = block(RainbowMetalModBlocks.PINK_700_PLATE);
	public static final RegistryObject<Item> PINK_800_PLATE = block(RainbowMetalModBlocks.PINK_800_PLATE);
	public static final RegistryObject<Item> PINK_900_PLATE = block(RainbowMetalModBlocks.PINK_900_PLATE);
	public static final RegistryObject<Item> PURPLE_50_PLATE = block(RainbowMetalModBlocks.PURPLE_50_PLATE);
	public static final RegistryObject<Item> PURPLE_100_PLATE = block(RainbowMetalModBlocks.PURPLE_100_PLATE);
	public static final RegistryObject<Item> PURPLE_200_PLATE = block(RainbowMetalModBlocks.PURPLE_200_PLATE);
	public static final RegistryObject<Item> PURPLE_300_PLATE = block(RainbowMetalModBlocks.PURPLE_300_PLATE);
	public static final RegistryObject<Item> PURPLE_400_PLATE = block(RainbowMetalModBlocks.PURPLE_400_PLATE);
	public static final RegistryObject<Item> PURPLE_500_PLATE = block(RainbowMetalModBlocks.PURPLE_500_PLATE);
	public static final RegistryObject<Item> PURPLE_600_PLATE = block(RainbowMetalModBlocks.PURPLE_600_PLATE);
	public static final RegistryObject<Item> PURPLE_700_PLATE = block(RainbowMetalModBlocks.PURPLE_700_PLATE);
	public static final RegistryObject<Item> PURPLE_800_PLATE = block(RainbowMetalModBlocks.PURPLE_800_PLATE);
	public static final RegistryObject<Item> PURPLE_900_PLATE = block(RainbowMetalModBlocks.PURPLE_900_PLATE);
	public static final RegistryObject<Item> RED_50_PLATE = block(RainbowMetalModBlocks.RED_50_PLATE);
	public static final RegistryObject<Item> RED_100_PLATE = block(RainbowMetalModBlocks.RED_100_PLATE);
	public static final RegistryObject<Item> RED_200_PLATE = block(RainbowMetalModBlocks.RED_200_PLATE);
	public static final RegistryObject<Item> RED_300_PLATE = block(RainbowMetalModBlocks.RED_300_PLATE);
	public static final RegistryObject<Item> RED_400_PLATE = block(RainbowMetalModBlocks.RED_400_PLATE);
	public static final RegistryObject<Item> RED_500_PLATE = block(RainbowMetalModBlocks.RED_500_PLATE);
	public static final RegistryObject<Item> RED_600_PLATE = block(RainbowMetalModBlocks.RED_600_PLATE);
	public static final RegistryObject<Item> RED_700_PLATE = block(RainbowMetalModBlocks.RED_700_PLATE);
	public static final RegistryObject<Item> RED_800_PLATE = block(RainbowMetalModBlocks.RED_800_PLATE);
	public static final RegistryObject<Item> RED_900_PLATE = block(RainbowMetalModBlocks.RED_900_PLATE);
	public static final RegistryObject<Item> YELLOW_50_PLATE = block(RainbowMetalModBlocks.YELLOW_50_PLATE);
	public static final RegistryObject<Item> YELLOW_100_PLATE = block(RainbowMetalModBlocks.YELLOW_100_PLATE);
	public static final RegistryObject<Item> YELLOW_200_PLATE = block(RainbowMetalModBlocks.YELLOW_200_PLATE);
	public static final RegistryObject<Item> YELLOW_300_PLATE = block(RainbowMetalModBlocks.YELLOW_300_PLATE);
	public static final RegistryObject<Item> YELLOW_400_PLATE = block(RainbowMetalModBlocks.YELLOW_400_PLATE);
	public static final RegistryObject<Item> YELLOW_500_PLATE = block(RainbowMetalModBlocks.YELLOW_500_PLATE);
	public static final RegistryObject<Item> YELLOW_600_PLATE = block(RainbowMetalModBlocks.YELLOW_600_PLATE);
	public static final RegistryObject<Item> YELLOW_700_PLATE = block(RainbowMetalModBlocks.YELLOW_700_PLATE);
	public static final RegistryObject<Item> YELLOW_800_PLATE = block(RainbowMetalModBlocks.YELLOW_800_PLATE);
	public static final RegistryObject<Item> YELLOW_900_PLATE = block(RainbowMetalModBlocks.YELLOW_900_PLATE);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
