
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package rainbow_metal.init;

import rainbow_metal.block.Yellow900PlateBlock;
import rainbow_metal.block.Yellow800PlateBlock;
import rainbow_metal.block.Yellow700PlateBlock;
import rainbow_metal.block.Yellow600PlateBlock;
import rainbow_metal.block.Yellow50PlateBlock;
import rainbow_metal.block.Yellow500PlateBlock;
import rainbow_metal.block.Yellow400PlateBlock;
import rainbow_metal.block.Yellow300PlateBlock;
import rainbow_metal.block.Yellow200PlateBlock;
import rainbow_metal.block.Yellow100PlateBlock;
import rainbow_metal.block.Red900PlateBlock;
import rainbow_metal.block.Red800PlateBlock;
import rainbow_metal.block.Red700PlateBlock;
import rainbow_metal.block.Red600PlateBlock;
import rainbow_metal.block.Red50PlateBlock;
import rainbow_metal.block.Red500PlateBlock;
import rainbow_metal.block.Red400PlateBlock;
import rainbow_metal.block.Red300PlateBlock;
import rainbow_metal.block.Red200PlateBlock;
import rainbow_metal.block.Red100PlateBlock;
import rainbow_metal.block.Purple900PlateBlock;
import rainbow_metal.block.Purple800PlateBlock;
import rainbow_metal.block.Purple700PlateBlock;
import rainbow_metal.block.Purple600PlateBlock;
import rainbow_metal.block.Purple50PlateBlock;
import rainbow_metal.block.Purple500PlateBlock;
import rainbow_metal.block.Purple400PlateBlock;
import rainbow_metal.block.Purple300PlateBlock;
import rainbow_metal.block.Purple200PlateBlock;
import rainbow_metal.block.Purple100PlateBlock;
import rainbow_metal.block.Pink900PlateBlock;
import rainbow_metal.block.Pink800PlateBlock;
import rainbow_metal.block.Pink700PlateBlock;
import rainbow_metal.block.Pink600PlateBlock;
import rainbow_metal.block.Pink50PlateBlock;
import rainbow_metal.block.Pink500PlateBlock;
import rainbow_metal.block.Pink400PlateBlock;
import rainbow_metal.block.Pink300PlateBlock;
import rainbow_metal.block.Pink200PlateBlock;
import rainbow_metal.block.Pink100PlateBlock;
import rainbow_metal.block.Orange900PlateBlock;
import rainbow_metal.block.Orange800PlateBlock;
import rainbow_metal.block.Orange700PlateBlock;
import rainbow_metal.block.Orange600PlateBlock;
import rainbow_metal.block.Orange50PlateBlock;
import rainbow_metal.block.Orange500PlateBlock;
import rainbow_metal.block.Orange400PlateBlock;
import rainbow_metal.block.Orange300PlateBlock;
import rainbow_metal.block.Orange200PlateBlock;
import rainbow_metal.block.Orange100PlateBlock;
import rainbow_metal.block.Magenta900PlateBlock;
import rainbow_metal.block.Magenta800PlateBlock;
import rainbow_metal.block.Magenta700PlateBlock;
import rainbow_metal.block.Magenta600PlateBlock;
import rainbow_metal.block.Magenta50PlateBlock;
import rainbow_metal.block.Magenta500PlateBlock;
import rainbow_metal.block.Magenta400PlateBlock;
import rainbow_metal.block.Magenta300PlateBlock;
import rainbow_metal.block.Magenta200PlateBlock;
import rainbow_metal.block.Magenta100PlateBlock;
import rainbow_metal.block.Lime900PlateBlock;
import rainbow_metal.block.Lime800PlateBlock;
import rainbow_metal.block.Lime700PlateBlock;
import rainbow_metal.block.Lime600PlateBlock;
import rainbow_metal.block.Lime50PlateBlock;
import rainbow_metal.block.Lime500PlateBlock;
import rainbow_metal.block.Lime400PlateBlock;
import rainbow_metal.block.Lime300PlateBlock;
import rainbow_metal.block.Lime200PlateBlock;
import rainbow_metal.block.Lime100PlateBlock;
import rainbow_metal.block.LightGray900PlateBlock;
import rainbow_metal.block.LightGray800PlateBlock;
import rainbow_metal.block.LightGray700PlateBlock;
import rainbow_metal.block.LightGray600PlateBlock;
import rainbow_metal.block.LightGray50PlateBlock;
import rainbow_metal.block.LightGray500PlateBlock;
import rainbow_metal.block.LightGray400PlateBlock;
import rainbow_metal.block.LightGray300PlateBlock;
import rainbow_metal.block.LightGray200PlateBlock;
import rainbow_metal.block.LightGray100PlateBlock;
import rainbow_metal.block.LightBlue900PlateBlock;
import rainbow_metal.block.LightBlue800PlateBlock;
import rainbow_metal.block.LightBlue700PlateBlock;
import rainbow_metal.block.LightBlue600PlateBlock;
import rainbow_metal.block.LightBlue50PlateBlock;
import rainbow_metal.block.LightBlue500PlateBlock;
import rainbow_metal.block.LightBlue400PlateBlock;
import rainbow_metal.block.LightBlue300PlateBlock;
import rainbow_metal.block.LightBlue200PlateBlock;
import rainbow_metal.block.LightBlue100PlateBlock;
import rainbow_metal.block.Green900PlateBlock;
import rainbow_metal.block.Green800PlateBlock;
import rainbow_metal.block.Green700PlateBlock;
import rainbow_metal.block.Green600PlateBlock;
import rainbow_metal.block.Green50PlateBlock;
import rainbow_metal.block.Green500PlateBlock;
import rainbow_metal.block.Green400PlateBlock;
import rainbow_metal.block.Green300PlateBlock;
import rainbow_metal.block.Green200PlateBlock;
import rainbow_metal.block.Green100PlateBlock;
import rainbow_metal.block.Gray900PlateBlock;
import rainbow_metal.block.Gray800PlateBlock;
import rainbow_metal.block.Gray700PlateBlock;
import rainbow_metal.block.Gray600PlateBlock;
import rainbow_metal.block.Gray50PlateBlock;
import rainbow_metal.block.Gray500PlateBlock;
import rainbow_metal.block.Gray400PlateBlock;
import rainbow_metal.block.Gray300PlateBlock;
import rainbow_metal.block.Gray200PlateBlock;
import rainbow_metal.block.Gray100PlateBlock;
import rainbow_metal.block.Cyan900PlateBlock;
import rainbow_metal.block.Cyan800PlateBlock;
import rainbow_metal.block.Cyan700PlateBlock;
import rainbow_metal.block.Cyan600PlateBlock;
import rainbow_metal.block.Cyan50PlateBlock;
import rainbow_metal.block.Cyan500PlateBlock;
import rainbow_metal.block.Cyan400PlateBlock;
import rainbow_metal.block.Cyan300PlateBlock;
import rainbow_metal.block.Cyan200PlateBlock;
import rainbow_metal.block.Cyan100PlateBlock;
import rainbow_metal.block.Brown900PlateBlock;
import rainbow_metal.block.Brown800PlateBlock;
import rainbow_metal.block.Brown700PlateBlock;
import rainbow_metal.block.Brown600PlateBlock;
import rainbow_metal.block.Brown50PlateBlock;
import rainbow_metal.block.Brown500PlateBlock;
import rainbow_metal.block.Brown400PlateBlock;
import rainbow_metal.block.Brown300PlateBlock;
import rainbow_metal.block.Brown200PlateBlock;
import rainbow_metal.block.Brown100PlateBlock;
import rainbow_metal.block.Blue900PlateBlock;
import rainbow_metal.block.Blue800PlateBlock;
import rainbow_metal.block.Blue700PlateBlock;
import rainbow_metal.block.Blue600PlateBlock;
import rainbow_metal.block.Blue500PlateBlock;
import rainbow_metal.block.Blue400PlateBlock;
import rainbow_metal.block.Blue300PlateBlock;
import rainbow_metal.block.Blue200PlateBlock;

import rainbow_metal.RainbowMetalMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class RainbowMetalModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, RainbowMetalMod.MODID);
	public static final RegistryObject<Block> BLUE_200_PLATE = REGISTRY.register("blue_200_plate", () -> new Blue200PlateBlock());
	public static final RegistryObject<Block> BLUE_300_PLATE = REGISTRY.register("blue_300_plate", () -> new Blue300PlateBlock());
	public static final RegistryObject<Block> BLUE_400_PLATE = REGISTRY.register("blue_400_plate", () -> new Blue400PlateBlock());
	public static final RegistryObject<Block> BLUE_500_PLATE = REGISTRY.register("blue_500_plate", () -> new Blue500PlateBlock());
	public static final RegistryObject<Block> BLUE_600_PLATE = REGISTRY.register("blue_600_plate", () -> new Blue600PlateBlock());
	public static final RegistryObject<Block> BLUE_700_PLATE = REGISTRY.register("blue_700_plate", () -> new Blue700PlateBlock());
	public static final RegistryObject<Block> BLUE_800_PLATE = REGISTRY.register("blue_800_plate", () -> new Blue800PlateBlock());
	public static final RegistryObject<Block> BLUE_900_PLATE = REGISTRY.register("blue_900_plate", () -> new Blue900PlateBlock());
	public static final RegistryObject<Block> BROWN_50_PLATE = REGISTRY.register("brown_50_plate", () -> new Brown50PlateBlock());
	public static final RegistryObject<Block> BROWN_100_PLATE = REGISTRY.register("brown_100_plate", () -> new Brown100PlateBlock());
	public static final RegistryObject<Block> BROWN_200_PLATE = REGISTRY.register("brown_200_plate", () -> new Brown200PlateBlock());
	public static final RegistryObject<Block> BROWN_300_PLATE = REGISTRY.register("brown_300_plate", () -> new Brown300PlateBlock());
	public static final RegistryObject<Block> BROWN_400_PLATE = REGISTRY.register("brown_400_plate", () -> new Brown400PlateBlock());
	public static final RegistryObject<Block> BROWN_500_PLATE = REGISTRY.register("brown_500_plate", () -> new Brown500PlateBlock());
	public static final RegistryObject<Block> BROWN_600_PLATE = REGISTRY.register("brown_600_plate", () -> new Brown600PlateBlock());
	public static final RegistryObject<Block> BROWN_700_PLATE = REGISTRY.register("brown_700_plate", () -> new Brown700PlateBlock());
	public static final RegistryObject<Block> BROWN_800_PLATE = REGISTRY.register("brown_800_plate", () -> new Brown800PlateBlock());
	public static final RegistryObject<Block> BROWN_900_PLATE = REGISTRY.register("brown_900_plate", () -> new Brown900PlateBlock());
	public static final RegistryObject<Block> CYAN_50_PLATE = REGISTRY.register("cyan_50_plate", () -> new Cyan50PlateBlock());
	public static final RegistryObject<Block> CYAN_100_PLATE = REGISTRY.register("cyan_100_plate", () -> new Cyan100PlateBlock());
	public static final RegistryObject<Block> CYAN_200_PLATE = REGISTRY.register("cyan_200_plate", () -> new Cyan200PlateBlock());
	public static final RegistryObject<Block> CYAN_300_PLATE = REGISTRY.register("cyan_300_plate", () -> new Cyan300PlateBlock());
	public static final RegistryObject<Block> CYAN_400_PLATE = REGISTRY.register("cyan_400_plate", () -> new Cyan400PlateBlock());
	public static final RegistryObject<Block> CYAN_500_PLATE = REGISTRY.register("cyan_500_plate", () -> new Cyan500PlateBlock());
	public static final RegistryObject<Block> CYAN_600_PLATE = REGISTRY.register("cyan_600_plate", () -> new Cyan600PlateBlock());
	public static final RegistryObject<Block> CYAN_700_PLATE = REGISTRY.register("cyan_700_plate", () -> new Cyan700PlateBlock());
	public static final RegistryObject<Block> CYAN_800_PLATE = REGISTRY.register("cyan_800_plate", () -> new Cyan800PlateBlock());
	public static final RegistryObject<Block> CYAN_900_PLATE = REGISTRY.register("cyan_900_plate", () -> new Cyan900PlateBlock());
	public static final RegistryObject<Block> GRAY_50_PLATE = REGISTRY.register("gray_50_plate", () -> new Gray50PlateBlock());
	public static final RegistryObject<Block> GRAY_100_PLATE = REGISTRY.register("gray_100_plate", () -> new Gray100PlateBlock());
	public static final RegistryObject<Block> GRAY_200_PLATE = REGISTRY.register("gray_200_plate", () -> new Gray200PlateBlock());
	public static final RegistryObject<Block> GRAY_300_PLATE = REGISTRY.register("gray_300_plate", () -> new Gray300PlateBlock());
	public static final RegistryObject<Block> GRAY_400_PLATE = REGISTRY.register("gray_400_plate", () -> new Gray400PlateBlock());
	public static final RegistryObject<Block> GRAY_500_PLATE = REGISTRY.register("gray_500_plate", () -> new Gray500PlateBlock());
	public static final RegistryObject<Block> GRAY_600_PLATE = REGISTRY.register("gray_600_plate", () -> new Gray600PlateBlock());
	public static final RegistryObject<Block> GRAY_700_PLATE = REGISTRY.register("gray_700_plate", () -> new Gray700PlateBlock());
	public static final RegistryObject<Block> GRAY_800_PLATE = REGISTRY.register("gray_800_plate", () -> new Gray800PlateBlock());
	public static final RegistryObject<Block> GRAY_900_PLATE = REGISTRY.register("gray_900_plate", () -> new Gray900PlateBlock());
	public static final RegistryObject<Block> GREEN_50_PLATE = REGISTRY.register("green_50_plate", () -> new Green50PlateBlock());
	public static final RegistryObject<Block> GREEN_100_PLATE = REGISTRY.register("green_100_plate", () -> new Green100PlateBlock());
	public static final RegistryObject<Block> GREEN_200_PLATE = REGISTRY.register("green_200_plate", () -> new Green200PlateBlock());
	public static final RegistryObject<Block> GREEN_300_PLATE = REGISTRY.register("green_300_plate", () -> new Green300PlateBlock());
	public static final RegistryObject<Block> GREEN_400_PLATE = REGISTRY.register("green_400_plate", () -> new Green400PlateBlock());
	public static final RegistryObject<Block> GREEN_500_PLATE = REGISTRY.register("green_500_plate", () -> new Green500PlateBlock());
	public static final RegistryObject<Block> GREEN_600_PLATE = REGISTRY.register("green_600_plate", () -> new Green600PlateBlock());
	public static final RegistryObject<Block> GREEN_700_PLATE = REGISTRY.register("green_700_plate", () -> new Green700PlateBlock());
	public static final RegistryObject<Block> GREEN_800_PLATE = REGISTRY.register("green_800_plate", () -> new Green800PlateBlock());
	public static final RegistryObject<Block> GREEN_900_PLATE = REGISTRY.register("green_900_plate", () -> new Green900PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_50_PLATE = REGISTRY.register("light_blue_50_plate", () -> new LightBlue50PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_100_PLATE = REGISTRY.register("light_blue_100_plate", () -> new LightBlue100PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_200_PLATE = REGISTRY.register("light_blue_200_plate", () -> new LightBlue200PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_300_PLATE = REGISTRY.register("light_blue_300_plate", () -> new LightBlue300PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_400_PLATE = REGISTRY.register("light_blue_400_plate", () -> new LightBlue400PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_500_PLATE = REGISTRY.register("light_blue_500_plate", () -> new LightBlue500PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_600_PLATE = REGISTRY.register("light_blue_600_plate", () -> new LightBlue600PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_700_PLATE = REGISTRY.register("light_blue_700_plate", () -> new LightBlue700PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_800_PLATE = REGISTRY.register("light_blue_800_plate", () -> new LightBlue800PlateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_900_PLATE = REGISTRY.register("light_blue_900_plate", () -> new LightBlue900PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_50_PLATE = REGISTRY.register("light_gray_50_plate", () -> new LightGray50PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_100_PLATE = REGISTRY.register("light_gray_100_plate", () -> new LightGray100PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_200_PLATE = REGISTRY.register("light_gray_200_plate", () -> new LightGray200PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_300_PLATE = REGISTRY.register("light_gray_300_plate", () -> new LightGray300PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_400_PLATE = REGISTRY.register("light_gray_400_plate", () -> new LightGray400PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_500_PLATE = REGISTRY.register("light_gray_500_plate", () -> new LightGray500PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_600_PLATE = REGISTRY.register("light_gray_600_plate", () -> new LightGray600PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_700_PLATE = REGISTRY.register("light_gray_700_plate", () -> new LightGray700PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_800_PLATE = REGISTRY.register("light_gray_800_plate", () -> new LightGray800PlateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_900_PLATE = REGISTRY.register("light_gray_900_plate", () -> new LightGray900PlateBlock());
	public static final RegistryObject<Block> LIME_50_PLATE = REGISTRY.register("lime_50_plate", () -> new Lime50PlateBlock());
	public static final RegistryObject<Block> LIME_100_PLATE = REGISTRY.register("lime_100_plate", () -> new Lime100PlateBlock());
	public static final RegistryObject<Block> LIME_200_PLATE = REGISTRY.register("lime_200_plate", () -> new Lime200PlateBlock());
	public static final RegistryObject<Block> LIME_300_PLATE = REGISTRY.register("lime_300_plate", () -> new Lime300PlateBlock());
	public static final RegistryObject<Block> LIME_400_PLATE = REGISTRY.register("lime_400_plate", () -> new Lime400PlateBlock());
	public static final RegistryObject<Block> LIME_500_PLATE = REGISTRY.register("lime_500_plate", () -> new Lime500PlateBlock());
	public static final RegistryObject<Block> LIME_600_PLATE = REGISTRY.register("lime_600_plate", () -> new Lime600PlateBlock());
	public static final RegistryObject<Block> LIME_700_PLATE = REGISTRY.register("lime_700_plate", () -> new Lime700PlateBlock());
	public static final RegistryObject<Block> LIME_800_PLATE = REGISTRY.register("lime_800_plate", () -> new Lime800PlateBlock());
	public static final RegistryObject<Block> LIME_900_PLATE = REGISTRY.register("lime_900_plate", () -> new Lime900PlateBlock());
	public static final RegistryObject<Block> MAGENTA_50_PLATE = REGISTRY.register("magenta_50_plate", () -> new Magenta50PlateBlock());
	public static final RegistryObject<Block> MAGENTA_100_PLATE = REGISTRY.register("magenta_100_plate", () -> new Magenta100PlateBlock());
	public static final RegistryObject<Block> MAGENTA_200_PLATE = REGISTRY.register("magenta_200_plate", () -> new Magenta200PlateBlock());
	public static final RegistryObject<Block> MAGENTA_300_PLATE = REGISTRY.register("magenta_300_plate", () -> new Magenta300PlateBlock());
	public static final RegistryObject<Block> MAGENTA_400_PLATE = REGISTRY.register("magenta_400_plate", () -> new Magenta400PlateBlock());
	public static final RegistryObject<Block> MAGENTA_500_PLATE = REGISTRY.register("magenta_500_plate", () -> new Magenta500PlateBlock());
	public static final RegistryObject<Block> MAGENTA_600_PLATE = REGISTRY.register("magenta_600_plate", () -> new Magenta600PlateBlock());
	public static final RegistryObject<Block> MAGENTA_700_PLATE = REGISTRY.register("magenta_700_plate", () -> new Magenta700PlateBlock());
	public static final RegistryObject<Block> MAGENTA_800_PLATE = REGISTRY.register("magenta_800_plate", () -> new Magenta800PlateBlock());
	public static final RegistryObject<Block> MAGENTA_900_PLATE = REGISTRY.register("magenta_900_plate", () -> new Magenta900PlateBlock());
	public static final RegistryObject<Block> ORANGE_50_PLATE = REGISTRY.register("orange_50_plate", () -> new Orange50PlateBlock());
	public static final RegistryObject<Block> ORANGE_100_PLATE = REGISTRY.register("orange_100_plate", () -> new Orange100PlateBlock());
	public static final RegistryObject<Block> ORANGE_200_PLATE = REGISTRY.register("orange_200_plate", () -> new Orange200PlateBlock());
	public static final RegistryObject<Block> ORANGE_300_PLATE = REGISTRY.register("orange_300_plate", () -> new Orange300PlateBlock());
	public static final RegistryObject<Block> ORANGE_400_PLATE = REGISTRY.register("orange_400_plate", () -> new Orange400PlateBlock());
	public static final RegistryObject<Block> ORANGE_500_PLATE = REGISTRY.register("orange_500_plate", () -> new Orange500PlateBlock());
	public static final RegistryObject<Block> ORANGE_600_PLATE = REGISTRY.register("orange_600_plate", () -> new Orange600PlateBlock());
	public static final RegistryObject<Block> ORANGE_700_PLATE = REGISTRY.register("orange_700_plate", () -> new Orange700PlateBlock());
	public static final RegistryObject<Block> ORANGE_800_PLATE = REGISTRY.register("orange_800_plate", () -> new Orange800PlateBlock());
	public static final RegistryObject<Block> ORANGE_900_PLATE = REGISTRY.register("orange_900_plate", () -> new Orange900PlateBlock());
	public static final RegistryObject<Block> PINK_50_PLATE = REGISTRY.register("pink_50_plate", () -> new Pink50PlateBlock());
	public static final RegistryObject<Block> PINK_100_PLATE = REGISTRY.register("pink_100_plate", () -> new Pink100PlateBlock());
	public static final RegistryObject<Block> PINK_200_PLATE = REGISTRY.register("pink_200_plate", () -> new Pink200PlateBlock());
	public static final RegistryObject<Block> PINK_300_PLATE = REGISTRY.register("pink_300_plate", () -> new Pink300PlateBlock());
	public static final RegistryObject<Block> PINK_400_PLATE = REGISTRY.register("pink_400_plate", () -> new Pink400PlateBlock());
	public static final RegistryObject<Block> PINK_500_PLATE = REGISTRY.register("pink_500_plate", () -> new Pink500PlateBlock());
	public static final RegistryObject<Block> PINK_600_PLATE = REGISTRY.register("pink_600_plate", () -> new Pink600PlateBlock());
	public static final RegistryObject<Block> PINK_700_PLATE = REGISTRY.register("pink_700_plate", () -> new Pink700PlateBlock());
	public static final RegistryObject<Block> PINK_800_PLATE = REGISTRY.register("pink_800_plate", () -> new Pink800PlateBlock());
	public static final RegistryObject<Block> PINK_900_PLATE = REGISTRY.register("pink_900_plate", () -> new Pink900PlateBlock());
	public static final RegistryObject<Block> PURPLE_50_PLATE = REGISTRY.register("purple_50_plate", () -> new Purple50PlateBlock());
	public static final RegistryObject<Block> PURPLE_100_PLATE = REGISTRY.register("purple_100_plate", () -> new Purple100PlateBlock());
	public static final RegistryObject<Block> PURPLE_200_PLATE = REGISTRY.register("purple_200_plate", () -> new Purple200PlateBlock());
	public static final RegistryObject<Block> PURPLE_300_PLATE = REGISTRY.register("purple_300_plate", () -> new Purple300PlateBlock());
	public static final RegistryObject<Block> PURPLE_400_PLATE = REGISTRY.register("purple_400_plate", () -> new Purple400PlateBlock());
	public static final RegistryObject<Block> PURPLE_500_PLATE = REGISTRY.register("purple_500_plate", () -> new Purple500PlateBlock());
	public static final RegistryObject<Block> PURPLE_600_PLATE = REGISTRY.register("purple_600_plate", () -> new Purple600PlateBlock());
	public static final RegistryObject<Block> PURPLE_700_PLATE = REGISTRY.register("purple_700_plate", () -> new Purple700PlateBlock());
	public static final RegistryObject<Block> PURPLE_800_PLATE = REGISTRY.register("purple_800_plate", () -> new Purple800PlateBlock());
	public static final RegistryObject<Block> PURPLE_900_PLATE = REGISTRY.register("purple_900_plate", () -> new Purple900PlateBlock());
	public static final RegistryObject<Block> RED_50_PLATE = REGISTRY.register("red_50_plate", () -> new Red50PlateBlock());
	public static final RegistryObject<Block> RED_100_PLATE = REGISTRY.register("red_100_plate", () -> new Red100PlateBlock());
	public static final RegistryObject<Block> RED_200_PLATE = REGISTRY.register("red_200_plate", () -> new Red200PlateBlock());
	public static final RegistryObject<Block> RED_300_PLATE = REGISTRY.register("red_300_plate", () -> new Red300PlateBlock());
	public static final RegistryObject<Block> RED_400_PLATE = REGISTRY.register("red_400_plate", () -> new Red400PlateBlock());
	public static final RegistryObject<Block> RED_500_PLATE = REGISTRY.register("red_500_plate", () -> new Red500PlateBlock());
	public static final RegistryObject<Block> RED_600_PLATE = REGISTRY.register("red_600_plate", () -> new Red600PlateBlock());
	public static final RegistryObject<Block> RED_700_PLATE = REGISTRY.register("red_700_plate", () -> new Red700PlateBlock());
	public static final RegistryObject<Block> RED_800_PLATE = REGISTRY.register("red_800_plate", () -> new Red800PlateBlock());
	public static final RegistryObject<Block> RED_900_PLATE = REGISTRY.register("red_900_plate", () -> new Red900PlateBlock());
	public static final RegistryObject<Block> YELLOW_50_PLATE = REGISTRY.register("yellow_50_plate", () -> new Yellow50PlateBlock());
	public static final RegistryObject<Block> YELLOW_100_PLATE = REGISTRY.register("yellow_100_plate", () -> new Yellow100PlateBlock());
	public static final RegistryObject<Block> YELLOW_200_PLATE = REGISTRY.register("yellow_200_plate", () -> new Yellow200PlateBlock());
	public static final RegistryObject<Block> YELLOW_300_PLATE = REGISTRY.register("yellow_300_plate", () -> new Yellow300PlateBlock());
	public static final RegistryObject<Block> YELLOW_400_PLATE = REGISTRY.register("yellow_400_plate", () -> new Yellow400PlateBlock());
	public static final RegistryObject<Block> YELLOW_500_PLATE = REGISTRY.register("yellow_500_plate", () -> new Yellow500PlateBlock());
	public static final RegistryObject<Block> YELLOW_600_PLATE = REGISTRY.register("yellow_600_plate", () -> new Yellow600PlateBlock());
	public static final RegistryObject<Block> YELLOW_700_PLATE = REGISTRY.register("yellow_700_plate", () -> new Yellow700PlateBlock());
	public static final RegistryObject<Block> YELLOW_800_PLATE = REGISTRY.register("yellow_800_plate", () -> new Yellow800PlateBlock());
	public static final RegistryObject<Block> YELLOW_900_PLATE = REGISTRY.register("yellow_900_plate", () -> new Yellow900PlateBlock());
}
