
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package rainbow.init;

import rainbow.RainbowMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class RainbowModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, RainbowMod.MODID);
	public static final RegistryObject<Item> BLUE_100_BLOCK = block(RainbowModBlocks.BLUE_100_BLOCK);
	public static final RegistryObject<Item> BLUE_50_BLOCK = block(RainbowModBlocks.BLUE_50_BLOCK);
	public static final RegistryObject<Item> BLUE_200_BLOCK = block(RainbowModBlocks.BLUE_200_BLOCK);
	public static final RegistryObject<Item> BLUE_300_BLOCK = block(RainbowModBlocks.BLUE_300_BLOCK);
	public static final RegistryObject<Item> BLUE_400_BLOCK = block(RainbowModBlocks.BLUE_400_BLOCK);
	public static final RegistryObject<Item> BLUE_500_BLOCK = block(RainbowModBlocks.BLUE_500_BLOCK);
	public static final RegistryObject<Item> BLUE_600_BLOCK = block(RainbowModBlocks.BLUE_600_BLOCK);
	public static final RegistryObject<Item> BLUE_700_BLOCK = block(RainbowModBlocks.BLUE_700_BLOCK);
	public static final RegistryObject<Item> BLUE_800_BLOCK = block(RainbowModBlocks.BLUE_800_BLOCK);
	public static final RegistryObject<Item> BLUE_900_BLOCK = block(RainbowModBlocks.BLUE_900_BLOCK);
	public static final RegistryObject<Item> BROWN_50_BLOCK = block(RainbowModBlocks.BROWN_50_BLOCK);
	public static final RegistryObject<Item> BROWN_100_BLOCK = block(RainbowModBlocks.BROWN_100_BLOCK);
	public static final RegistryObject<Item> BROWN_200_BLOCK = block(RainbowModBlocks.BROWN_200_BLOCK);
	public static final RegistryObject<Item> BROWN_300_BLOCK = block(RainbowModBlocks.BROWN_300_BLOCK);
	public static final RegistryObject<Item> BROWN_400_BLOCK = block(RainbowModBlocks.BROWN_400_BLOCK);
	public static final RegistryObject<Item> BROWN_500_BLOCK = block(RainbowModBlocks.BROWN_500_BLOCK);
	public static final RegistryObject<Item> BROWN_600_BLOCK = block(RainbowModBlocks.BROWN_600_BLOCK);
	public static final RegistryObject<Item> BROWN_700_BLOCK = block(RainbowModBlocks.BROWN_700_BLOCK);
	public static final RegistryObject<Item> BROWN_800_BLOCK = block(RainbowModBlocks.BROWN_800_BLOCK);
	public static final RegistryObject<Item> BROWN_900_BLOCK = block(RainbowModBlocks.BROWN_900_BLOCK);
	public static final RegistryObject<Item> CYAN_50_BLOCK = block(RainbowModBlocks.CYAN_50_BLOCK);
	public static final RegistryObject<Item> CYAN_100_BLOCK = block(RainbowModBlocks.CYAN_100_BLOCK);
	public static final RegistryObject<Item> CYAN_200_BLOCK = block(RainbowModBlocks.CYAN_200_BLOCK);
	public static final RegistryObject<Item> CYAN_300_BLOCK = block(RainbowModBlocks.CYAN_300_BLOCK);
	public static final RegistryObject<Item> CYAN_400_BLOCK = block(RainbowModBlocks.CYAN_400_BLOCK);
	public static final RegistryObject<Item> CYAN_500_BLOCK = block(RainbowModBlocks.CYAN_500_BLOCK);
	public static final RegistryObject<Item> CYAN_600_BLOCK = block(RainbowModBlocks.CYAN_600_BLOCK);
	public static final RegistryObject<Item> CYAN_700_BLOCK = block(RainbowModBlocks.CYAN_700_BLOCK);
	public static final RegistryObject<Item> CYAN_800_BLOCK = block(RainbowModBlocks.CYAN_800_BLOCK);
	public static final RegistryObject<Item> CYAN_900_BLOCK = block(RainbowModBlocks.CYAN_900_BLOCK);
	public static final RegistryObject<Item> GRAY_50_BLOCK = block(RainbowModBlocks.GRAY_50_BLOCK);
	public static final RegistryObject<Item> GRAY_100_BLOCK = block(RainbowModBlocks.GRAY_100_BLOCK);
	public static final RegistryObject<Item> GRAY_200_BLOCK = block(RainbowModBlocks.GRAY_200_BLOCK);
	public static final RegistryObject<Item> GRAY_300_BLOCK = block(RainbowModBlocks.GRAY_300_BLOCK);
	public static final RegistryObject<Item> GRAY_400_BLOCK = block(RainbowModBlocks.GRAY_400_BLOCK);
	public static final RegistryObject<Item> GRAY_500_BLOCK = block(RainbowModBlocks.GRAY_500_BLOCK);
	public static final RegistryObject<Item> GRAY_600_BLOCK = block(RainbowModBlocks.GRAY_600_BLOCK);
	public static final RegistryObject<Item> GRAY_700_BLOCK = block(RainbowModBlocks.GRAY_700_BLOCK);
	public static final RegistryObject<Item> GRAY_800_BLOCK = block(RainbowModBlocks.GRAY_800_BLOCK);
	public static final RegistryObject<Item> GRAY_900_BLOCK = block(RainbowModBlocks.GRAY_900_BLOCK);
	public static final RegistryObject<Item> GREEN_50_BLOCK = block(RainbowModBlocks.GREEN_50_BLOCK);
	public static final RegistryObject<Item> GREEN_100_BLOCK = block(RainbowModBlocks.GREEN_100_BLOCK);
	public static final RegistryObject<Item> GREEN_200_BLOCK = block(RainbowModBlocks.GREEN_200_BLOCK);
	public static final RegistryObject<Item> GREEN_300_BLOCK = block(RainbowModBlocks.GREEN_300_BLOCK);
	public static final RegistryObject<Item> GREEN_400_BLOCK = block(RainbowModBlocks.GREEN_400_BLOCK);
	public static final RegistryObject<Item> GREEN_500_BLOCK = block(RainbowModBlocks.GREEN_500_BLOCK);
	public static final RegistryObject<Item> GREEN_600_BLOCK = block(RainbowModBlocks.GREEN_600_BLOCK);
	public static final RegistryObject<Item> GREEN_700_BLOCK = block(RainbowModBlocks.GREEN_700_BLOCK);
	public static final RegistryObject<Item> GREEN_800_BLOCK = block(RainbowModBlocks.GREEN_800_BLOCK);
	public static final RegistryObject<Item> GREEN_900_BLOCK = block(RainbowModBlocks.GREEN_900_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_50_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_50_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_100_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_100_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_200_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_200_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_300_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_300_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_400_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_400_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_500_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_500_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_600_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_600_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_700_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_700_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_800_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_800_BLOCK);
	public static final RegistryObject<Item> LIGHT_BLUE_900_BLOCK = block(RainbowModBlocks.LIGHT_BLUE_900_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_50_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_50_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_100_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_100_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_200_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_200_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_300_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_300_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_400_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_400_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_500_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_500_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_600_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_600_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_700_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_700_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_800_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_800_BLOCK);
	public static final RegistryObject<Item> LIGHT_GRAY_900_BLOCK = block(RainbowModBlocks.LIGHT_GRAY_900_BLOCK);
	public static final RegistryObject<Item> LIME_50_BLOCK = block(RainbowModBlocks.LIME_50_BLOCK);
	public static final RegistryObject<Item> LIME_100_BLOCK = block(RainbowModBlocks.LIME_100_BLOCK);
	public static final RegistryObject<Item> LIME_200_BLOCK = block(RainbowModBlocks.LIME_200_BLOCK);
	public static final RegistryObject<Item> LIME_300_BLOCK = block(RainbowModBlocks.LIME_300_BLOCK);
	public static final RegistryObject<Item> LIME_400_BLOCK = block(RainbowModBlocks.LIME_400_BLOCK);
	public static final RegistryObject<Item> LIME_500_BLOCK = block(RainbowModBlocks.LIME_500_BLOCK);
	public static final RegistryObject<Item> LIME_600_BLOCK = block(RainbowModBlocks.LIME_600_BLOCK);
	public static final RegistryObject<Item> LIME_700_BLOCK = block(RainbowModBlocks.LIME_700_BLOCK);
	public static final RegistryObject<Item> LIME_800_BLOCK = block(RainbowModBlocks.LIME_800_BLOCK);
	public static final RegistryObject<Item> LIME_900_BLOCK = block(RainbowModBlocks.LIME_900_BLOCK);
	public static final RegistryObject<Item> MAGENTA_50_BLOCK = block(RainbowModBlocks.MAGENTA_50_BLOCK);
	public static final RegistryObject<Item> MAGENTA_100_BLOCK = block(RainbowModBlocks.MAGENTA_100_BLOCK);
	public static final RegistryObject<Item> MAGENTA_200_BLOCK = block(RainbowModBlocks.MAGENTA_200_BLOCK);
	public static final RegistryObject<Item> MAGENTA_300_BLOCK = block(RainbowModBlocks.MAGENTA_300_BLOCK);
	public static final RegistryObject<Item> MAGENTA_400_BLOCK = block(RainbowModBlocks.MAGENTA_400_BLOCK);
	public static final RegistryObject<Item> MAGENTA_500_BLOCK = block(RainbowModBlocks.MAGENTA_500_BLOCK);
	public static final RegistryObject<Item> MAGENTA_600_BLOCK = block(RainbowModBlocks.MAGENTA_600_BLOCK);
	public static final RegistryObject<Item> MAGENTA_700_BLOCK = block(RainbowModBlocks.MAGENTA_700_BLOCK);
	public static final RegistryObject<Item> MAGENTA_800_BLOCK = block(RainbowModBlocks.MAGENTA_800_BLOCK);
	public static final RegistryObject<Item> MAGENTA_900_BLOCK = block(RainbowModBlocks.MAGENTA_900_BLOCK);
	public static final RegistryObject<Item> ORANGE_50_BLOCK = block(RainbowModBlocks.ORANGE_50_BLOCK);
	public static final RegistryObject<Item> ORANGE_100_BLOCK = block(RainbowModBlocks.ORANGE_100_BLOCK);
	public static final RegistryObject<Item> ORANGE_200_BLOCK = block(RainbowModBlocks.ORANGE_200_BLOCK);
	public static final RegistryObject<Item> ORANGE_300_BLOCK = block(RainbowModBlocks.ORANGE_300_BLOCK);
	public static final RegistryObject<Item> ORANGE_400_BLOCK = block(RainbowModBlocks.ORANGE_400_BLOCK);
	public static final RegistryObject<Item> ORANGE_500_BLOCK = block(RainbowModBlocks.ORANGE_500_BLOCK);
	public static final RegistryObject<Item> ORANGE_600_BLOCK = block(RainbowModBlocks.ORANGE_600_BLOCK);
	public static final RegistryObject<Item> ORANGE_700_BLOCK = block(RainbowModBlocks.ORANGE_700_BLOCK);
	public static final RegistryObject<Item> ORANGE_800_BLOCK = block(RainbowModBlocks.ORANGE_800_BLOCK);
	public static final RegistryObject<Item> ORANGE_900_BLOCK = block(RainbowModBlocks.ORANGE_900_BLOCK);
	public static final RegistryObject<Item> PINK_50_BLOCK = block(RainbowModBlocks.PINK_50_BLOCK);
	public static final RegistryObject<Item> PINK_100_BLOCK = block(RainbowModBlocks.PINK_100_BLOCK);
	public static final RegistryObject<Item> PINK_200_BLOCK = block(RainbowModBlocks.PINK_200_BLOCK);
	public static final RegistryObject<Item> PINK_300_BLOCK = block(RainbowModBlocks.PINK_300_BLOCK);
	public static final RegistryObject<Item> PINK_400_BLOCK = block(RainbowModBlocks.PINK_400_BLOCK);
	public static final RegistryObject<Item> PINK_500_BLOCK = block(RainbowModBlocks.PINK_500_BLOCK);
	public static final RegistryObject<Item> PINK_600_BLOCK = block(RainbowModBlocks.PINK_600_BLOCK);
	public static final RegistryObject<Item> PINK_700_BLOCK = block(RainbowModBlocks.PINK_700_BLOCK);
	public static final RegistryObject<Item> PINK_800_BLOCK = block(RainbowModBlocks.PINK_800_BLOCK);
	public static final RegistryObject<Item> PINK_900_BLOCK = block(RainbowModBlocks.PINK_900_BLOCK);
	public static final RegistryObject<Item> PURPLE_50_BLOCK = block(RainbowModBlocks.PURPLE_50_BLOCK);
	public static final RegistryObject<Item> PURPLE_100_BLOCK = block(RainbowModBlocks.PURPLE_100_BLOCK);
	public static final RegistryObject<Item> PURPLE_200_BLOCK = block(RainbowModBlocks.PURPLE_200_BLOCK);
	public static final RegistryObject<Item> PURPLE_300_BLOCK = block(RainbowModBlocks.PURPLE_300_BLOCK);
	public static final RegistryObject<Item> PURPLE_400_BLOCK = block(RainbowModBlocks.PURPLE_400_BLOCK);
	public static final RegistryObject<Item> PURPLE_500_BLOCK = block(RainbowModBlocks.PURPLE_500_BLOCK);
	public static final RegistryObject<Item> PURPLE_600_BLOCK = block(RainbowModBlocks.PURPLE_600_BLOCK);
	public static final RegistryObject<Item> PURPLE_700_BLOCK = block(RainbowModBlocks.PURPLE_700_BLOCK);
	public static final RegistryObject<Item> PURPLE_800_BLOCK = block(RainbowModBlocks.PURPLE_800_BLOCK);
	public static final RegistryObject<Item> PURPLE_900_BLOCK = block(RainbowModBlocks.PURPLE_900_BLOCK);
	public static final RegistryObject<Item> RED_50_BLOCK = block(RainbowModBlocks.RED_50_BLOCK);
	public static final RegistryObject<Item> RED_100_BLOCK = block(RainbowModBlocks.RED_100_BLOCK);
	public static final RegistryObject<Item> RED_200_BLOCK = block(RainbowModBlocks.RED_200_BLOCK);
	public static final RegistryObject<Item> RED_300_BLOCK = block(RainbowModBlocks.RED_300_BLOCK);
	public static final RegistryObject<Item> RED_400_BLOCK = block(RainbowModBlocks.RED_400_BLOCK);
	public static final RegistryObject<Item> RED_500_BLOCK = block(RainbowModBlocks.RED_500_BLOCK);
	public static final RegistryObject<Item> RED_600_BLOCK = block(RainbowModBlocks.RED_600_BLOCK);
	public static final RegistryObject<Item> RED_700_BLOCK = block(RainbowModBlocks.RED_700_BLOCK);
	public static final RegistryObject<Item> RED_800_BLOCK = block(RainbowModBlocks.RED_800_BLOCK);
	public static final RegistryObject<Item> RED_900_BLOCK = block(RainbowModBlocks.RED_900_BLOCK);
	public static final RegistryObject<Item> YELLOW_50_BLOCK = block(RainbowModBlocks.YELLOW_50_BLOCK);
	public static final RegistryObject<Item> YELLOW_100_BLOCK = block(RainbowModBlocks.YELLOW_100_BLOCK);
	public static final RegistryObject<Item> YELLOW_200_BLOCK = block(RainbowModBlocks.YELLOW_200_BLOCK);
	public static final RegistryObject<Item> YELLOW_300_BLOCK = block(RainbowModBlocks.YELLOW_300_BLOCK);
	public static final RegistryObject<Item> YELLOW_400_BLOCK = block(RainbowModBlocks.YELLOW_400_BLOCK);
	public static final RegistryObject<Item> YELLOW_500_BLOCK = block(RainbowModBlocks.YELLOW_500_BLOCK);
	public static final RegistryObject<Item> YELLOW_600_BLOCK = block(RainbowModBlocks.YELLOW_600_BLOCK);
	public static final RegistryObject<Item> YELLOW_700_BLOCK = block(RainbowModBlocks.YELLOW_700_BLOCK);
	public static final RegistryObject<Item> YELLOW_800_BLOCK = block(RainbowModBlocks.YELLOW_800_BLOCK);
	public static final RegistryObject<Item> YELLOW_900_BLOCK = block(RainbowModBlocks.YELLOW_900_BLOCK);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
