import type { IMaterial } from "../../types/index.ts";
import { channelPercentage } from "../_utils.ts";
export const materials: IMaterial[] = [
  {
    uuid: "82596330-64ea-4f9c-bdb2-7080036ae1db",
    name: { en_US: "Plastic" },
    label: "rough",
    normal: "brick_normal",
    sound: "note.snare",
    friction: (idx: number) => Math.min(0.9, Math.max(0.1, idx * 0.1)),
    minimumLevel: 50,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [25, 50, 75, 100],
    explosionResistance: (idx: number) => Math.min(1, Math.max(0, idx * 0.1)),
    lightAbsorption: (_itr: number) => 15,
    lightEmission: () => 0,
    metalness: () => 0,
    emissive: () => 0,
    roughness: (idx: number) => channelPercentage(100 - idx),
    opacity: () => 1,
    shading: [
      // {
      //   texture: "plastic_soft-light",
      //   blend: "soft-light",
      // },
      // {
      //   blend: "multiply",
      //   texture: "plastic_multiply",
      // },
    ],
    octaves: 3,
  },
  {
    uuid: "baf7e0ba-57e4-440e-9557-abcca23f65d4",
    name: { en_US: "Metallic" },
    label: "metal",
    normal: "metal_normal",
    sound: "note.iron_xylophone",
    friction: (idx: number) => Math.min(0.7, Math.max(0.01, idx * 0.1)),
    minimumLevel: 50,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [25, 50, 75, 100],
    explosionResistance: (idx: number) => Math.min(1, Math.max(0, idx * 0.1)),
    lightAbsorption: (itr: number) =>
      Math.min(15, Math.max(0, 15 * (itr / 100))),
    lightEmission: () => 0,
    metalness: (idx: number) => channelPercentage(idx),
    emissive: () => 0,
    roughness: () => 0,
    opacity: () => 1,
    shading: [
      // {
      //   blend: ["color-dodge", "overlay"],
      //   texture: "metal_overlay",
      // },
      // {
      //   blend: ["color-burn", "overlay"],
      //   texture: "metal_reflectivity",
      // },
    ],
    octaves: 3,
  },
  {
    uuid: "4ecaa878-a15c-4d97-b73b-f2d80a7954eb",
    name: {
      en_US: "Planks",
    },
    label: "wood",
    normal: "planks_normal",
    sound: "wood",
    friction: () => 0.6,
    minimumLevel: 60,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [100],
    explosionResistance: () => 1,
    lightAbsorption: () => 15,
    lightEmission: () => 0,
    metalness: () => 0,
    emissive: () => 0,
    roughness: () => 80,
    opacity: () => 1,
    shading: [{
      blend: "overlay",
      texture: "planks_multiply",
    }],
    octaves: 3,
  },
  {
    uuid: "1bfedaa6-eec2-48ad-b1d0-ace6aede6f95",
    name: {
      en_US: "Stud",
    },
    label: "stud",
    normal: "pyramid_normal",
    sound: "itemframe",
    friction: () => 0.5,
    minimumLevel: 60,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [25],
    explosionResistance: () => 1,
    lightAbsorption: () => 15,
    lightEmission: () => 0,
    metalness: () => 255,
    emissive: () => 0,
    roughness: () => 25,
    opacity: () => 1,
    octaves: 3,
  },
  {
    uuid: "1a4619d9-1897-4b0c-8fe6-eb5c99dc5074",
    name: {
      en_US: "Brick",
    },
    label: "brick",
    normal: "big_brick_normal",
    mer: "big_brick_mer",
    sound: "stone",
    friction: () => 0.5,
    minimumLevel: 60,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [25],
    explosionResistance: () => 1,
    lightAbsorption: () => 15,
    lightEmission: () => 0,
    metalness: () => 255,
    emissive: () => 0,
    roughness: () => 25,
    opacity: () => 1,
    shading: [{
      blend: "multiply",
      texture: "big_brick",
    }],
    octaves: 3,
  },
  {
    uuid: "4a049e57-cb34-4973-8ae5-b4f0ba2f9335",
    name: {
      en_US: "Brick Lit",
    },
    label: "brick_lit",
    normal: "big_brick_normal",
    mer: "big_brick_lit_mer",
    sound: "glass",
    friction: () => 0.5,
    minimumLevel: 60,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [25],
    explosionResistance: () => 1,
    lightAbsorption: () => 15,
    lightEmission: () => 7,
    metalness: () => 255,
    emissive: () => 0,
    roughness: () => 25,
    opacity: () => 1,
    shading: [{
      blend: "multiply",
      texture: "big_brick",
    }],
    octaves: 3,
  },
  {
    uuid: "8e0e0737-d02d-42f4-8298-14e2374347e8",
    name: { en_US: "Glowing" },
    label: "emissive",
    normal: "block_normal",
    sound: "chime.amethyst_block",
    friction: () => 0.5,
    minimumLevel: 0,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [0, 25, 50, 75, 100],
    explosionResistance: () => 0,
    lightAbsorption: (_itr: number) => 10,
    lightEmission: (itr: number) =>
      Math.max(0, Math.min(15, Math.ceil(itr * 0.9))),
    metalness: () => 0,
    emissive: (idx: number) =>
      Math.max(50, Math.min(80, Math.floor(channelPercentage(idx) * 0.666))),
    roughness: () => channelPercentage(30),
    opacity: () => 1,
    shading: [{
      blend: "overlay",
      texture: "glowing",
    }],
    octaves: 3,
  },
  {
    uuid: "aed2fc55-cfc4-4048-8609-8304c59759c0",
    name: { en_US: "Glass" },
    label: "glass",
    normal: "block_normal",
    sound: "glass",
    friction: () => 0.3,
    minimumLevel: 40,
    maximumLevel: 80,
    endStep: 90,
    step: 20,
    steps: [50, 70],
    explosionResistance: (itr: number) => itr > 50 ? 0.5 : 0,
    lightAbsorption: () => 1,
    lightEmission: () => 0,
    metalness: () => 0,
    emissive: () => 0,
    roughness: () => channelPercentage(25),
    opacity: (itr: number) => itr > 50 ? 0.65 : 0.5,
    shading: [{
      blend: ["overlay", "multiply"],
      texture: "glass",
    }],
    octaves: 3,
  },
  {
    uuid: "9f576c0a-6a7d-402d-84c0-2257faba4fd3",
    name: { en_US: "Glass Pane" },
    label: "glass_pane",
    normal: "block_normal",
    sound: "glass",
    geometry: "pane",
    friction: () => 0.2,
    minimumLevel: 45,
    maximumLevel: 55,
    endStep: 90,
    step: 5,
    steps: [50],
    explosionResistance: () => 0,
    lightAbsorption: () => 1,
    lightEmission: () => 0,
    metalness: () => 0,
    emissive: () => 0,
    roughness: () => 15,
    opacity: (itr: number) => Math.min(0.6, Math.max(0.499, itr * 0.01)),
    shading: [{
      blend: ["overlay", "multiply"],
      texture: "glass",
    }],
    octaves: 3,
  },
  {
    uuid: "e7620d80-112c-41db-b159-31446174f76c",
    name: { en_US: "Dot" },
    label: "dot",
    normal: "dot_normal",
    mer: "dot_mer",
    sound: "pop",
    friction: (_idx: number) => 0.5,
    minimumLevel: 50,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [50],
    explosionResistance: (_idx: number) => 1,
    lightAbsorption: (_itr: number) => 15,
    lightEmission: () => 0,
    metalness: () => 0,
    emissive: () => 0,
    roughness: (_idx: number) => 55,
    opacity: () => 1,
    shading: [
      {
        texture: "dot_multiply",
        blend: "multiply",
      },
    ],
    octaves: 3,
  },
  {
    uuid: "884b3443-0241-41a7-90e3-a53ba215a279",
    name: { en_US: "Lit Dot" },
    label: "lit_dot",
    normal: "dot_normal",
    mer: "lit_dot_mer",
    sound: "pop",
    friction: (_idx: number) => 0.5,
    minimumLevel: 50,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [50],
    explosionResistance: (_idx: number) => 1,
    lightAbsorption: (_itr: number) => 0,
    lightEmission: () => 0.5,
    metalness: () => 0,
    emissive: () => 0,
    roughness: (_idx: number) => 55,
    opacity: () => 1,
    shading: [
      {
        texture: "dot_multiply",
        blend: "multiply",
      },
    ],
    octaves: 3,
  },
  {
    uuid: "238f73d9-5261-456c-a8f4-a82683261dba",
    name: { en_US: "Negative" },
    label: "negative",
    normal: "negative_normal",
    mer: "negative_mer",
    sound: "glass",
    friction: (_idx: number) => 0.4,
    minimumLevel: 50,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [50],
    explosionResistance: (_idx: number) => 1,
    lightAbsorption: (_itr: number) => 0,
    lightEmission: () => 0.4,
    metalness: () => 0,
    emissive: () => 0,
    roughness: (_idx: number) => 55,
    opacity: () => 1,
    shading: [
      {
        texture: "negative_overlay",
        blend: "multiply",
      },
    ],
    octaves: 2,
  },
  {
    uuid: "783e37fe-3a37-48a4-9acb-90b2840608df",
    name: { en_US: "Positive" },
    label: "positive",
    normal: "positive_normal",
    mer: "positive_mer",
    sound: "glass",
    friction: (_idx: number) => 0.6,
    minimumLevel: 50,
    maximumLevel: 100,
    endStep: 100,
    step: 25,
    steps: [50],
    explosionResistance: (_idx: number) => 1,
    lightAbsorption: (_itr: number) => 0,
    lightEmission: () => 0.4,
    metalness: () => 0,
    emissive: () => 0,
    roughness: (_idx: number) => 55,
    opacity: () => 1,
    shading: [
      {
        texture: "positive_dodge",
        blend: "multiply",
      },
    ],
    octaves: 2,
  },
];
