modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="rainbow_glass"
version="3.0.0"
displayName="RAINBOW III!!! Glass"
displayURL="https://github.com/jasonjgardner/minecraft-rtx-rainbow"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Jason J. Gardner"

[[dependencies.rainbow_glass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




