# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# check these at https://fabricmc.net/develop/
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.9

# Mod Properties
mod_version=3.1.2
maven_group=co.jasongardner
archives_base_name=rainbowiii

# Dependencies
# Using 1.21.4 Fabric API for forward compatibility with 1.21.11
fabric_version=0.110.5+1.21.4
