
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package rainbow_lamp.init;

import rainbow_lamp.block.Yellow900LampBlock;
import rainbow_lamp.block.Yellow800LampBlock;
import rainbow_lamp.block.Yellow700LampBlock;
import rainbow_lamp.block.Yellow600LampBlock;
import rainbow_lamp.block.Yellow50LampBlock;
import rainbow_lamp.block.Yellow500LampBlock;
import rainbow_lamp.block.Yellow400LampBlock;
import rainbow_lamp.block.Yellow300LampBlock;
import rainbow_lamp.block.Yellow200LampBlock;
import rainbow_lamp.block.Yellow100LampBlock;
import rainbow_lamp.block.Red900LampBlock;
import rainbow_lamp.block.Red800LampBlock;
import rainbow_lamp.block.Red700LampBlock;
import rainbow_lamp.block.Red600LampBlock;
import rainbow_lamp.block.Red50LampBlock;
import rainbow_lamp.block.Red500LampBlock;
import rainbow_lamp.block.Red400LampBlock;
import rainbow_lamp.block.Red300LampBlock;
import rainbow_lamp.block.Red200LampBlock;
import rainbow_lamp.block.Red100LampBlock;
import rainbow_lamp.block.Purple900LampBlock;
import rainbow_lamp.block.Purple800LampBlock;
import rainbow_lamp.block.Purple700LampBlock;
import rainbow_lamp.block.Purple600LampBlock;
import rainbow_lamp.block.Purple50LampBlock;
import rainbow_lamp.block.Purple500LampBlock;
import rainbow_lamp.block.Purple400LampBlock;
import rainbow_lamp.block.Purple300LampBlock;
import rainbow_lamp.block.Purple200LampBlock;
import rainbow_lamp.block.Purple100LampBlock;
import rainbow_lamp.block.Pink900LampBlock;
import rainbow_lamp.block.Pink800LampBlock;
import rainbow_lamp.block.Pink700LampBlock;
import rainbow_lamp.block.Pink600LampBlock;
import rainbow_lamp.block.Pink50LampBlock;
import rainbow_lamp.block.Pink500LampBlock;
import rainbow_lamp.block.Pink400LampBlock;
import rainbow_lamp.block.Pink300LampBlock;
import rainbow_lamp.block.Pink200LampBlock;
import rainbow_lamp.block.Pink100LampBlock;
import rainbow_lamp.block.Orange900LampBlock;
import rainbow_lamp.block.Orange800LampBlock;
import rainbow_lamp.block.Orange700LampBlock;
import rainbow_lamp.block.Orange600LampBlock;
import rainbow_lamp.block.Orange50LampBlock;
import rainbow_lamp.block.Orange500LampBlock;
import rainbow_lamp.block.Orange400LampBlock;
import rainbow_lamp.block.Orange300LampBlock;
import rainbow_lamp.block.Orange200LampBlock;
import rainbow_lamp.block.Orange100LampBlock;
import rainbow_lamp.block.Magenta900LampBlock;
import rainbow_lamp.block.Magenta800LampBlock;
import rainbow_lamp.block.Magenta700LampBlock;
import rainbow_lamp.block.Magenta600LampBlock;
import rainbow_lamp.block.Magenta50LampBlock;
import rainbow_lamp.block.Magenta500LampBlock;
import rainbow_lamp.block.Magenta400LampBlock;
import rainbow_lamp.block.Magenta300LampBlock;
import rainbow_lamp.block.Magenta200LampBlock;
import rainbow_lamp.block.Magenta100LampBlock;
import rainbow_lamp.block.Lime900LampBlock;
import rainbow_lamp.block.Lime800LampBlock;
import rainbow_lamp.block.Lime700LampBlock;
import rainbow_lamp.block.Lime600LampBlock;
import rainbow_lamp.block.Lime50LampBlock;
import rainbow_lamp.block.Lime500LampBlock;
import rainbow_lamp.block.Lime400LampBlock;
import rainbow_lamp.block.Lime300LampBlock;
import rainbow_lamp.block.Lime200LampBlock;
import rainbow_lamp.block.Lime100LampBlock;
import rainbow_lamp.block.LightGray900LampBlock;
import rainbow_lamp.block.LightGray800LampBlock;
import rainbow_lamp.block.LightGray700LampBlock;
import rainbow_lamp.block.LightGray600LampBlock;
import rainbow_lamp.block.LightGray50LampBlock;
import rainbow_lamp.block.LightGray500LampBlock;
import rainbow_lamp.block.LightGray400LampBlock;
import rainbow_lamp.block.LightGray300LampBlock;
import rainbow_lamp.block.LightGray200LampBlock;
import rainbow_lamp.block.LightGray100LampBlock;
import rainbow_lamp.block.LightBlue900LampBlock;
import rainbow_lamp.block.LightBlue800LampBlock;
import rainbow_lamp.block.LightBlue700LampBlock;
import rainbow_lamp.block.LightBlue600LampBlock;
import rainbow_lamp.block.LightBlue50LampBlock;
import rainbow_lamp.block.LightBlue500LampBlock;
import rainbow_lamp.block.LightBlue400LampBlock;
import rainbow_lamp.block.LightBlue300LampBlock;
import rainbow_lamp.block.LightBlue200LampBlock;
import rainbow_lamp.block.LightBlue100LampBlock;
import rainbow_lamp.block.Green900LampBlock;
import rainbow_lamp.block.Green800LampBlock;
import rainbow_lamp.block.Green700LampBlock;
import rainbow_lamp.block.Green600LampBlock;
import rainbow_lamp.block.Green50LampBlock;
import rainbow_lamp.block.Green500LampBlock;
import rainbow_lamp.block.Green400LampBlock;
import rainbow_lamp.block.Green300LampBlock;
import rainbow_lamp.block.Green200LampBlock;
import rainbow_lamp.block.Green100LampBlock;
import rainbow_lamp.block.Gray900LampBlock;
import rainbow_lamp.block.Gray800LampBlock;
import rainbow_lamp.block.Gray700LampBlock;
import rainbow_lamp.block.Gray600LampBlock;
import rainbow_lamp.block.Gray50LampBlock;
import rainbow_lamp.block.Gray500LampBlock;
import rainbow_lamp.block.Gray400LampBlock;
import rainbow_lamp.block.Gray300LampBlock;
import rainbow_lamp.block.Gray200LampBlock;
import rainbow_lamp.block.Gray100LampBlock;
import rainbow_lamp.block.Cyan900LampBlock;
import rainbow_lamp.block.Cyan800LampBlock;
import rainbow_lamp.block.Cyan700LampBlock;
import rainbow_lamp.block.Cyan600LampBlock;
import rainbow_lamp.block.Cyan50LampBlock;
import rainbow_lamp.block.Cyan500LampBlock;
import rainbow_lamp.block.Cyan400LampBlock;
import rainbow_lamp.block.Cyan300LampBlock;
import rainbow_lamp.block.Cyan200LampBlock;
import rainbow_lamp.block.Cyan100LampBlock;
import rainbow_lamp.block.Brown900LampBlock;
import rainbow_lamp.block.Brown800LampBlock;
import rainbow_lamp.block.Brown700LampBlock;
import rainbow_lamp.block.Brown600LampBlock;
import rainbow_lamp.block.Brown50LampBlock;
import rainbow_lamp.block.Brown500LampBlock;
import rainbow_lamp.block.Brown400LampBlock;
import rainbow_lamp.block.Brown300LampBlock;
import rainbow_lamp.block.Brown200LampBlock;
import rainbow_lamp.block.Brown100LampBlock;
import rainbow_lamp.block.Blue900LampBlock;
import rainbow_lamp.block.Blue800LampBlock;
import rainbow_lamp.block.Blue700LampBlock;
import rainbow_lamp.block.Blue600LampBlock;
import rainbow_lamp.block.Blue50LampBlock;
import rainbow_lamp.block.Blue500LampBlock;
import rainbow_lamp.block.Blue400LampBlock;
import rainbow_lamp.block.Blue300LampBlock;
import rainbow_lamp.block.Blue200LampBlock;
import rainbow_lamp.block.Blue100LampBlock;

import rainbow_lamp.RainbowLampMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class RainbowLampModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, RainbowLampMod.MODID);
	public static final RegistryObject<Block> BLUE_100_LAMP = REGISTRY.register("blue_100_lamp", () -> new Blue100LampBlock());
	public static final RegistryObject<Block> BLUE_50_LAMP = REGISTRY.register("blue_50_lamp", () -> new Blue50LampBlock());
	public static final RegistryObject<Block> BLUE_200_LAMP = REGISTRY.register("blue_200_lamp", () -> new Blue200LampBlock());
	public static final RegistryObject<Block> BLUE_300_LAMP = REGISTRY.register("blue_300_lamp", () -> new Blue300LampBlock());
	public static final RegistryObject<Block> BLUE_400_LAMP = REGISTRY.register("blue_400_lamp", () -> new Blue400LampBlock());
	public static final RegistryObject<Block> BLUE_500_LAMP = REGISTRY.register("blue_500_lamp", () -> new Blue500LampBlock());
	public static final RegistryObject<Block> BLUE_600_LAMP = REGISTRY.register("blue_600_lamp", () -> new Blue600LampBlock());
	public static final RegistryObject<Block> BLUE_700_LAMP = REGISTRY.register("blue_700_lamp", () -> new Blue700LampBlock());
	public static final RegistryObject<Block> BLUE_800_LAMP = REGISTRY.register("blue_800_lamp", () -> new Blue800LampBlock());
	public static final RegistryObject<Block> BLUE_900_LAMP = REGISTRY.register("blue_900_lamp", () -> new Blue900LampBlock());
	public static final RegistryObject<Block> BROWN_50_LAMP = REGISTRY.register("brown_50_lamp", () -> new Brown50LampBlock());
	public static final RegistryObject<Block> BROWN_100_LAMP = REGISTRY.register("brown_100_lamp", () -> new Brown100LampBlock());
	public static final RegistryObject<Block> BROWN_200_LAMP = REGISTRY.register("brown_200_lamp", () -> new Brown200LampBlock());
	public static final RegistryObject<Block> BROWN_300_LAMP = REGISTRY.register("brown_300_lamp", () -> new Brown300LampBlock());
	public static final RegistryObject<Block> BROWN_400_LAMP = REGISTRY.register("brown_400_lamp", () -> new Brown400LampBlock());
	public static final RegistryObject<Block> BROWN_500_LAMP = REGISTRY.register("brown_500_lamp", () -> new Brown500LampBlock());
	public static final RegistryObject<Block> BROWN_600_LAMP = REGISTRY.register("brown_600_lamp", () -> new Brown600LampBlock());
	public static final RegistryObject<Block> BROWN_700_LAMP = REGISTRY.register("brown_700_lamp", () -> new Brown700LampBlock());
	public static final RegistryObject<Block> BROWN_800_LAMP = REGISTRY.register("brown_800_lamp", () -> new Brown800LampBlock());
	public static final RegistryObject<Block> BROWN_900_LAMP = REGISTRY.register("brown_900_lamp", () -> new Brown900LampBlock());
	public static final RegistryObject<Block> CYAN_50_LAMP = REGISTRY.register("cyan_50_lamp", () -> new Cyan50LampBlock());
	public static final RegistryObject<Block> CYAN_100_LAMP = REGISTRY.register("cyan_100_lamp", () -> new Cyan100LampBlock());
	public static final RegistryObject<Block> CYAN_200_LAMP = REGISTRY.register("cyan_200_lamp", () -> new Cyan200LampBlock());
	public static final RegistryObject<Block> CYAN_300_LAMP = REGISTRY.register("cyan_300_lamp", () -> new Cyan300LampBlock());
	public static final RegistryObject<Block> CYAN_400_LAMP = REGISTRY.register("cyan_400_lamp", () -> new Cyan400LampBlock());
	public static final RegistryObject<Block> CYAN_500_LAMP = REGISTRY.register("cyan_500_lamp", () -> new Cyan500LampBlock());
	public static final RegistryObject<Block> CYAN_600_LAMP = REGISTRY.register("cyan_600_lamp", () -> new Cyan600LampBlock());
	public static final RegistryObject<Block> CYAN_700_LAMP = REGISTRY.register("cyan_700_lamp", () -> new Cyan700LampBlock());
	public static final RegistryObject<Block> CYAN_800_LAMP = REGISTRY.register("cyan_800_lamp", () -> new Cyan800LampBlock());
	public static final RegistryObject<Block> CYAN_900_LAMP = REGISTRY.register("cyan_900_lamp", () -> new Cyan900LampBlock());
	public static final RegistryObject<Block> GRAY_50_LAMP = REGISTRY.register("gray_50_lamp", () -> new Gray50LampBlock());
	public static final RegistryObject<Block> GRAY_100_LAMP = REGISTRY.register("gray_100_lamp", () -> new Gray100LampBlock());
	public static final RegistryObject<Block> GRAY_200_LAMP = REGISTRY.register("gray_200_lamp", () -> new Gray200LampBlock());
	public static final RegistryObject<Block> GRAY_300_LAMP = REGISTRY.register("gray_300_lamp", () -> new Gray300LampBlock());
	public static final RegistryObject<Block> GRAY_400_LAMP = REGISTRY.register("gray_400_lamp", () -> new Gray400LampBlock());
	public static final RegistryObject<Block> GRAY_500_LAMP = REGISTRY.register("gray_500_lamp", () -> new Gray500LampBlock());
	public static final RegistryObject<Block> GRAY_600_LAMP = REGISTRY.register("gray_600_lamp", () -> new Gray600LampBlock());
	public static final RegistryObject<Block> GRAY_700_LAMP = REGISTRY.register("gray_700_lamp", () -> new Gray700LampBlock());
	public static final RegistryObject<Block> GRAY_800_LAMP = REGISTRY.register("gray_800_lamp", () -> new Gray800LampBlock());
	public static final RegistryObject<Block> GRAY_900_LAMP = REGISTRY.register("gray_900_lamp", () -> new Gray900LampBlock());
	public static final RegistryObject<Block> GREEN_50_LAMP = REGISTRY.register("green_50_lamp", () -> new Green50LampBlock());
	public static final RegistryObject<Block> GREEN_100_LAMP = REGISTRY.register("green_100_lamp", () -> new Green100LampBlock());
	public static final RegistryObject<Block> GREEN_200_LAMP = REGISTRY.register("green_200_lamp", () -> new Green200LampBlock());
	public static final RegistryObject<Block> GREEN_300_LAMP = REGISTRY.register("green_300_lamp", () -> new Green300LampBlock());
	public static final RegistryObject<Block> GREEN_400_LAMP = REGISTRY.register("green_400_lamp", () -> new Green400LampBlock());
	public static final RegistryObject<Block> GREEN_500_LAMP = REGISTRY.register("green_500_lamp", () -> new Green500LampBlock());
	public static final RegistryObject<Block> GREEN_600_LAMP = REGISTRY.register("green_600_lamp", () -> new Green600LampBlock());
	public static final RegistryObject<Block> GREEN_700_LAMP = REGISTRY.register("green_700_lamp", () -> new Green700LampBlock());
	public static final RegistryObject<Block> GREEN_800_LAMP = REGISTRY.register("green_800_lamp", () -> new Green800LampBlock());
	public static final RegistryObject<Block> GREEN_900_LAMP = REGISTRY.register("green_900_lamp", () -> new Green900LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_50_LAMP = REGISTRY.register("light_blue_50_lamp", () -> new LightBlue50LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_100_LAMP = REGISTRY.register("light_blue_100_lamp", () -> new LightBlue100LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_200_LAMP = REGISTRY.register("light_blue_200_lamp", () -> new LightBlue200LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_300_LAMP = REGISTRY.register("light_blue_300_lamp", () -> new LightBlue300LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_400_LAMP = REGISTRY.register("light_blue_400_lamp", () -> new LightBlue400LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_500_LAMP = REGISTRY.register("light_blue_500_lamp", () -> new LightBlue500LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_600_LAMP = REGISTRY.register("light_blue_600_lamp", () -> new LightBlue600LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_700_LAMP = REGISTRY.register("light_blue_700_lamp", () -> new LightBlue700LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_800_LAMP = REGISTRY.register("light_blue_800_lamp", () -> new LightBlue800LampBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_900_LAMP = REGISTRY.register("light_blue_900_lamp", () -> new LightBlue900LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_50_LAMP = REGISTRY.register("light_gray_50_lamp", () -> new LightGray50LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_100_LAMP = REGISTRY.register("light_gray_100_lamp", () -> new LightGray100LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_200_LAMP = REGISTRY.register("light_gray_200_lamp", () -> new LightGray200LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_300_LAMP = REGISTRY.register("light_gray_300_lamp", () -> new LightGray300LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_400_LAMP = REGISTRY.register("light_gray_400_lamp", () -> new LightGray400LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_500_LAMP = REGISTRY.register("light_gray_500_lamp", () -> new LightGray500LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_600_LAMP = REGISTRY.register("light_gray_600_lamp", () -> new LightGray600LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_700_LAMP = REGISTRY.register("light_gray_700_lamp", () -> new LightGray700LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_800_LAMP = REGISTRY.register("light_gray_800_lamp", () -> new LightGray800LampBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_900_LAMP = REGISTRY.register("light_gray_900_lamp", () -> new LightGray900LampBlock());
	public static final RegistryObject<Block> LIME_50_LAMP = REGISTRY.register("lime_50_lamp", () -> new Lime50LampBlock());
	public static final RegistryObject<Block> LIME_100_LAMP = REGISTRY.register("lime_100_lamp", () -> new Lime100LampBlock());
	public static final RegistryObject<Block> LIME_200_LAMP = REGISTRY.register("lime_200_lamp", () -> new Lime200LampBlock());
	public static final RegistryObject<Block> LIME_300_LAMP = REGISTRY.register("lime_300_lamp", () -> new Lime300LampBlock());
	public static final RegistryObject<Block> LIME_400_LAMP = REGISTRY.register("lime_400_lamp", () -> new Lime400LampBlock());
	public static final RegistryObject<Block> LIME_500_LAMP = REGISTRY.register("lime_500_lamp", () -> new Lime500LampBlock());
	public static final RegistryObject<Block> LIME_600_LAMP = REGISTRY.register("lime_600_lamp", () -> new Lime600LampBlock());
	public static final RegistryObject<Block> LIME_700_LAMP = REGISTRY.register("lime_700_lamp", () -> new Lime700LampBlock());
	public static final RegistryObject<Block> LIME_800_LAMP = REGISTRY.register("lime_800_lamp", () -> new Lime800LampBlock());
	public static final RegistryObject<Block> LIME_900_LAMP = REGISTRY.register("lime_900_lamp", () -> new Lime900LampBlock());
	public static final RegistryObject<Block> MAGENTA_50_LAMP = REGISTRY.register("magenta_50_lamp", () -> new Magenta50LampBlock());
	public static final RegistryObject<Block> MAGENTA_100_LAMP = REGISTRY.register("magenta_100_lamp", () -> new Magenta100LampBlock());
	public static final RegistryObject<Block> MAGENTA_200_LAMP = REGISTRY.register("magenta_200_lamp", () -> new Magenta200LampBlock());
	public static final RegistryObject<Block> MAGENTA_300_LAMP = REGISTRY.register("magenta_300_lamp", () -> new Magenta300LampBlock());
	public static final RegistryObject<Block> MAGENTA_400_LAMP = REGISTRY.register("magenta_400_lamp", () -> new Magenta400LampBlock());
	public static final RegistryObject<Block> MAGENTA_500_LAMP = REGISTRY.register("magenta_500_lamp", () -> new Magenta500LampBlock());
	public static final RegistryObject<Block> MAGENTA_600_LAMP = REGISTRY.register("magenta_600_lamp", () -> new Magenta600LampBlock());
	public static final RegistryObject<Block> MAGENTA_700_LAMP = REGISTRY.register("magenta_700_lamp", () -> new Magenta700LampBlock());
	public static final RegistryObject<Block> MAGENTA_800_LAMP = REGISTRY.register("magenta_800_lamp", () -> new Magenta800LampBlock());
	public static final RegistryObject<Block> MAGENTA_900_LAMP = REGISTRY.register("magenta_900_lamp", () -> new Magenta900LampBlock());
	public static final RegistryObject<Block> ORANGE_50_LAMP = REGISTRY.register("orange_50_lamp", () -> new Orange50LampBlock());
	public static final RegistryObject<Block> ORANGE_100_LAMP = REGISTRY.register("orange_100_lamp", () -> new Orange100LampBlock());
	public static final RegistryObject<Block> ORANGE_200_LAMP = REGISTRY.register("orange_200_lamp", () -> new Orange200LampBlock());
	public static final RegistryObject<Block> ORANGE_300_LAMP = REGISTRY.register("orange_300_lamp", () -> new Orange300LampBlock());
	public static final RegistryObject<Block> ORANGE_400_LAMP = REGISTRY.register("orange_400_lamp", () -> new Orange400LampBlock());
	public static final RegistryObject<Block> ORANGE_500_LAMP = REGISTRY.register("orange_500_lamp", () -> new Orange500LampBlock());
	public static final RegistryObject<Block> ORANGE_600_LAMP = REGISTRY.register("orange_600_lamp", () -> new Orange600LampBlock());
	public static final RegistryObject<Block> ORANGE_700_LAMP = REGISTRY.register("orange_700_lamp", () -> new Orange700LampBlock());
	public static final RegistryObject<Block> ORANGE_800_LAMP = REGISTRY.register("orange_800_lamp", () -> new Orange800LampBlock());
	public static final RegistryObject<Block> ORANGE_900_LAMP = REGISTRY.register("orange_900_lamp", () -> new Orange900LampBlock());
	public static final RegistryObject<Block> PINK_50_LAMP = REGISTRY.register("pink_50_lamp", () -> new Pink50LampBlock());
	public static final RegistryObject<Block> PINK_100_LAMP = REGISTRY.register("pink_100_lamp", () -> new Pink100LampBlock());
	public static final RegistryObject<Block> PINK_200_LAMP = REGISTRY.register("pink_200_lamp", () -> new Pink200LampBlock());
	public static final RegistryObject<Block> PINK_300_LAMP = REGISTRY.register("pink_300_lamp", () -> new Pink300LampBlock());
	public static final RegistryObject<Block> PINK_400_LAMP = REGISTRY.register("pink_400_lamp", () -> new Pink400LampBlock());
	public static final RegistryObject<Block> PINK_500_LAMP = REGISTRY.register("pink_500_lamp", () -> new Pink500LampBlock());
	public static final RegistryObject<Block> PINK_600_LAMP = REGISTRY.register("pink_600_lamp", () -> new Pink600LampBlock());
	public static final RegistryObject<Block> PINK_700_LAMP = REGISTRY.register("pink_700_lamp", () -> new Pink700LampBlock());
	public static final RegistryObject<Block> PINK_800_LAMP = REGISTRY.register("pink_800_lamp", () -> new Pink800LampBlock());
	public static final RegistryObject<Block> PINK_900_LAMP = REGISTRY.register("pink_900_lamp", () -> new Pink900LampBlock());
	public static final RegistryObject<Block> PURPLE_50_LAMP = REGISTRY.register("purple_50_lamp", () -> new Purple50LampBlock());
	public static final RegistryObject<Block> PURPLE_100_LAMP = REGISTRY.register("purple_100_lamp", () -> new Purple100LampBlock());
	public static final RegistryObject<Block> PURPLE_200_LAMP = REGISTRY.register("purple_200_lamp", () -> new Purple200LampBlock());
	public static final RegistryObject<Block> PURPLE_300_LAMP = REGISTRY.register("purple_300_lamp", () -> new Purple300LampBlock());
	public static final RegistryObject<Block> PURPLE_400_LAMP = REGISTRY.register("purple_400_lamp", () -> new Purple400LampBlock());
	public static final RegistryObject<Block> PURPLE_500_LAMP = REGISTRY.register("purple_500_lamp", () -> new Purple500LampBlock());
	public static final RegistryObject<Block> PURPLE_600_LAMP = REGISTRY.register("purple_600_lamp", () -> new Purple600LampBlock());
	public static final RegistryObject<Block> PURPLE_700_LAMP = REGISTRY.register("purple_700_lamp", () -> new Purple700LampBlock());
	public static final RegistryObject<Block> PURPLE_800_LAMP = REGISTRY.register("purple_800_lamp", () -> new Purple800LampBlock());
	public static final RegistryObject<Block> PURPLE_900_LAMP = REGISTRY.register("purple_900_lamp", () -> new Purple900LampBlock());
	public static final RegistryObject<Block> RED_50_LAMP = REGISTRY.register("red_50_lamp", () -> new Red50LampBlock());
	public static final RegistryObject<Block> RED_100_LAMP = REGISTRY.register("red_100_lamp", () -> new Red100LampBlock());
	public static final RegistryObject<Block> RED_200_LAMP = REGISTRY.register("red_200_lamp", () -> new Red200LampBlock());
	public static final RegistryObject<Block> RED_300_LAMP = REGISTRY.register("red_300_lamp", () -> new Red300LampBlock());
	public static final RegistryObject<Block> RED_400_LAMP = REGISTRY.register("red_400_lamp", () -> new Red400LampBlock());
	public static final RegistryObject<Block> RED_500_LAMP = REGISTRY.register("red_500_lamp", () -> new Red500LampBlock());
	public static final RegistryObject<Block> RED_600_LAMP = REGISTRY.register("red_600_lamp", () -> new Red600LampBlock());
	public static final RegistryObject<Block> RED_700_LAMP = REGISTRY.register("red_700_lamp", () -> new Red700LampBlock());
	public static final RegistryObject<Block> RED_800_LAMP = REGISTRY.register("red_800_lamp", () -> new Red800LampBlock());
	public static final RegistryObject<Block> RED_900_LAMP = REGISTRY.register("red_900_lamp", () -> new Red900LampBlock());
	public static final RegistryObject<Block> YELLOW_50_LAMP = REGISTRY.register("yellow_50_lamp", () -> new Yellow50LampBlock());
	public static final RegistryObject<Block> YELLOW_100_LAMP = REGISTRY.register("yellow_100_lamp", () -> new Yellow100LampBlock());
	public static final RegistryObject<Block> YELLOW_200_LAMP = REGISTRY.register("yellow_200_lamp", () -> new Yellow200LampBlock());
	public static final RegistryObject<Block> YELLOW_300_LAMP = REGISTRY.register("yellow_300_lamp", () -> new Yellow300LampBlock());
	public static final RegistryObject<Block> YELLOW_400_LAMP = REGISTRY.register("yellow_400_lamp", () -> new Yellow400LampBlock());
	public static final RegistryObject<Block> YELLOW_500_LAMP = REGISTRY.register("yellow_500_lamp", () -> new Yellow500LampBlock());
	public static final RegistryObject<Block> YELLOW_600_LAMP = REGISTRY.register("yellow_600_lamp", () -> new Yellow600LampBlock());
	public static final RegistryObject<Block> YELLOW_700_LAMP = REGISTRY.register("yellow_700_lamp", () -> new Yellow700LampBlock());
	public static final RegistryObject<Block> YELLOW_800_LAMP = REGISTRY.register("yellow_800_lamp", () -> new Yellow800LampBlock());
	public static final RegistryObject<Block> YELLOW_900_LAMP = REGISTRY.register("yellow_900_lamp", () -> new Yellow900LampBlock());
}
