
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package rainbow_lamp.init;

import rainbow_lamp.RainbowLampMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class RainbowLampModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, RainbowLampMod.MODID);
	public static final RegistryObject<Item> BLUE_100_LAMP = block(RainbowLampModBlocks.BLUE_100_LAMP);
	public static final RegistryObject<Item> BLUE_50_LAMP = block(RainbowLampModBlocks.BLUE_50_LAMP);
	public static final RegistryObject<Item> BLUE_200_LAMP = block(RainbowLampModBlocks.BLUE_200_LAMP);
	public static final RegistryObject<Item> BLUE_300_LAMP = block(RainbowLampModBlocks.BLUE_300_LAMP);
	public static final RegistryObject<Item> BLUE_400_LAMP = block(RainbowLampModBlocks.BLUE_400_LAMP);
	public static final RegistryObject<Item> BLUE_500_LAMP = block(RainbowLampModBlocks.BLUE_500_LAMP);
	public static final RegistryObject<Item> BLUE_600_LAMP = block(RainbowLampModBlocks.BLUE_600_LAMP);
	public static final RegistryObject<Item> BLUE_700_LAMP = block(RainbowLampModBlocks.BLUE_700_LAMP);
	public static final RegistryObject<Item> BLUE_800_LAMP = block(RainbowLampModBlocks.BLUE_800_LAMP);
	public static final RegistryObject<Item> BLUE_900_LAMP = block(RainbowLampModBlocks.BLUE_900_LAMP);
	public static final RegistryObject<Item> BROWN_50_LAMP = block(RainbowLampModBlocks.BROWN_50_LAMP);
	public static final RegistryObject<Item> BROWN_100_LAMP = block(RainbowLampModBlocks.BROWN_100_LAMP);
	public static final RegistryObject<Item> BROWN_200_LAMP = block(RainbowLampModBlocks.BROWN_200_LAMP);
	public static final RegistryObject<Item> BROWN_300_LAMP = block(RainbowLampModBlocks.BROWN_300_LAMP);
	public static final RegistryObject<Item> BROWN_400_LAMP = block(RainbowLampModBlocks.BROWN_400_LAMP);
	public static final RegistryObject<Item> BROWN_500_LAMP = block(RainbowLampModBlocks.BROWN_500_LAMP);
	public static final RegistryObject<Item> BROWN_600_LAMP = block(RainbowLampModBlocks.BROWN_600_LAMP);
	public static final RegistryObject<Item> BROWN_700_LAMP = block(RainbowLampModBlocks.BROWN_700_LAMP);
	public static final RegistryObject<Item> BROWN_800_LAMP = block(RainbowLampModBlocks.BROWN_800_LAMP);
	public static final RegistryObject<Item> BROWN_900_LAMP = block(RainbowLampModBlocks.BROWN_900_LAMP);
	public static final RegistryObject<Item> CYAN_50_LAMP = block(RainbowLampModBlocks.CYAN_50_LAMP);
	public static final RegistryObject<Item> CYAN_100_LAMP = block(RainbowLampModBlocks.CYAN_100_LAMP);
	public static final RegistryObject<Item> CYAN_200_LAMP = block(RainbowLampModBlocks.CYAN_200_LAMP);
	public static final RegistryObject<Item> CYAN_300_LAMP = block(RainbowLampModBlocks.CYAN_300_LAMP);
	public static final RegistryObject<Item> CYAN_400_LAMP = block(RainbowLampModBlocks.CYAN_400_LAMP);
	public static final RegistryObject<Item> CYAN_500_LAMP = block(RainbowLampModBlocks.CYAN_500_LAMP);
	public static final RegistryObject<Item> CYAN_600_LAMP = block(RainbowLampModBlocks.CYAN_600_LAMP);
	public static final RegistryObject<Item> CYAN_700_LAMP = block(RainbowLampModBlocks.CYAN_700_LAMP);
	public static final RegistryObject<Item> CYAN_800_LAMP = block(RainbowLampModBlocks.CYAN_800_LAMP);
	public static final RegistryObject<Item> CYAN_900_LAMP = block(RainbowLampModBlocks.CYAN_900_LAMP);
	public static final RegistryObject<Item> GRAY_50_LAMP = block(RainbowLampModBlocks.GRAY_50_LAMP);
	public static final RegistryObject<Item> GRAY_100_LAMP = block(RainbowLampModBlocks.GRAY_100_LAMP);
	public static final RegistryObject<Item> GRAY_200_LAMP = block(RainbowLampModBlocks.GRAY_200_LAMP);
	public static final RegistryObject<Item> GRAY_300_LAMP = block(RainbowLampModBlocks.GRAY_300_LAMP);
	public static final RegistryObject<Item> GRAY_400_LAMP = block(RainbowLampModBlocks.GRAY_400_LAMP);
	public static final RegistryObject<Item> GRAY_500_LAMP = block(RainbowLampModBlocks.GRAY_500_LAMP);
	public static final RegistryObject<Item> GRAY_600_LAMP = block(RainbowLampModBlocks.GRAY_600_LAMP);
	public static final RegistryObject<Item> GRAY_700_LAMP = block(RainbowLampModBlocks.GRAY_700_LAMP);
	public static final RegistryObject<Item> GRAY_800_LAMP = block(RainbowLampModBlocks.GRAY_800_LAMP);
	public static final RegistryObject<Item> GRAY_900_LAMP = block(RainbowLampModBlocks.GRAY_900_LAMP);
	public static final RegistryObject<Item> GREEN_50_LAMP = block(RainbowLampModBlocks.GREEN_50_LAMP);
	public static final RegistryObject<Item> GREEN_100_LAMP = block(RainbowLampModBlocks.GREEN_100_LAMP);
	public static final RegistryObject<Item> GREEN_200_LAMP = block(RainbowLampModBlocks.GREEN_200_LAMP);
	public static final RegistryObject<Item> GREEN_300_LAMP = block(RainbowLampModBlocks.GREEN_300_LAMP);
	public static final RegistryObject<Item> GREEN_400_LAMP = block(RainbowLampModBlocks.GREEN_400_LAMP);
	public static final RegistryObject<Item> GREEN_500_LAMP = block(RainbowLampModBlocks.GREEN_500_LAMP);
	public static final RegistryObject<Item> GREEN_600_LAMP = block(RainbowLampModBlocks.GREEN_600_LAMP);
	public static final RegistryObject<Item> GREEN_700_LAMP = block(RainbowLampModBlocks.GREEN_700_LAMP);
	public static final RegistryObject<Item> GREEN_800_LAMP = block(RainbowLampModBlocks.GREEN_800_LAMP);
	public static final RegistryObject<Item> GREEN_900_LAMP = block(RainbowLampModBlocks.GREEN_900_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_50_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_50_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_100_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_100_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_200_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_200_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_300_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_300_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_400_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_400_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_500_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_500_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_600_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_600_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_700_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_700_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_800_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_800_LAMP);
	public static final RegistryObject<Item> LIGHT_BLUE_900_LAMP = block(RainbowLampModBlocks.LIGHT_BLUE_900_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_50_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_50_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_100_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_100_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_200_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_200_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_300_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_300_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_400_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_400_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_500_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_500_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_600_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_600_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_700_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_700_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_800_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_800_LAMP);
	public static final RegistryObject<Item> LIGHT_GRAY_900_LAMP = block(RainbowLampModBlocks.LIGHT_GRAY_900_LAMP);
	public static final RegistryObject<Item> LIME_50_LAMP = block(RainbowLampModBlocks.LIME_50_LAMP);
	public static final RegistryObject<Item> LIME_100_LAMP = block(RainbowLampModBlocks.LIME_100_LAMP);
	public static final RegistryObject<Item> LIME_200_LAMP = block(RainbowLampModBlocks.LIME_200_LAMP);
	public static final RegistryObject<Item> LIME_300_LAMP = block(RainbowLampModBlocks.LIME_300_LAMP);
	public static final RegistryObject<Item> LIME_400_LAMP = block(RainbowLampModBlocks.LIME_400_LAMP);
	public static final RegistryObject<Item> LIME_500_LAMP = block(RainbowLampModBlocks.LIME_500_LAMP);
	public static final RegistryObject<Item> LIME_600_LAMP = block(RainbowLampModBlocks.LIME_600_LAMP);
	public static final RegistryObject<Item> LIME_700_LAMP = block(RainbowLampModBlocks.LIME_700_LAMP);
	public static final RegistryObject<Item> LIME_800_LAMP = block(RainbowLampModBlocks.LIME_800_LAMP);
	public static final RegistryObject<Item> LIME_900_LAMP = block(RainbowLampModBlocks.LIME_900_LAMP);
	public static final RegistryObject<Item> MAGENTA_50_LAMP = block(RainbowLampModBlocks.MAGENTA_50_LAMP);
	public static final RegistryObject<Item> MAGENTA_100_LAMP = block(RainbowLampModBlocks.MAGENTA_100_LAMP);
	public static final RegistryObject<Item> MAGENTA_200_LAMP = block(RainbowLampModBlocks.MAGENTA_200_LAMP);
	public static final RegistryObject<Item> MAGENTA_300_LAMP = block(RainbowLampModBlocks.MAGENTA_300_LAMP);
	public static final RegistryObject<Item> MAGENTA_400_LAMP = block(RainbowLampModBlocks.MAGENTA_400_LAMP);
	public static final RegistryObject<Item> MAGENTA_500_LAMP = block(RainbowLampModBlocks.MAGENTA_500_LAMP);
	public static final RegistryObject<Item> MAGENTA_600_LAMP = block(RainbowLampModBlocks.MAGENTA_600_LAMP);
	public static final RegistryObject<Item> MAGENTA_700_LAMP = block(RainbowLampModBlocks.MAGENTA_700_LAMP);
	public static final RegistryObject<Item> MAGENTA_800_LAMP = block(RainbowLampModBlocks.MAGENTA_800_LAMP);
	public static final RegistryObject<Item> MAGENTA_900_LAMP = block(RainbowLampModBlocks.MAGENTA_900_LAMP);
	public static final RegistryObject<Item> ORANGE_50_LAMP = block(RainbowLampModBlocks.ORANGE_50_LAMP);
	public static final RegistryObject<Item> ORANGE_100_LAMP = block(RainbowLampModBlocks.ORANGE_100_LAMP);
	public static final RegistryObject<Item> ORANGE_200_LAMP = block(RainbowLampModBlocks.ORANGE_200_LAMP);
	public static final RegistryObject<Item> ORANGE_300_LAMP = block(RainbowLampModBlocks.ORANGE_300_LAMP);
	public static final RegistryObject<Item> ORANGE_400_LAMP = block(RainbowLampModBlocks.ORANGE_400_LAMP);
	public static final RegistryObject<Item> ORANGE_500_LAMP = block(RainbowLampModBlocks.ORANGE_500_LAMP);
	public static final RegistryObject<Item> ORANGE_600_LAMP = block(RainbowLampModBlocks.ORANGE_600_LAMP);
	public static final RegistryObject<Item> ORANGE_700_LAMP = block(RainbowLampModBlocks.ORANGE_700_LAMP);
	public static final RegistryObject<Item> ORANGE_800_LAMP = block(RainbowLampModBlocks.ORANGE_800_LAMP);
	public static final RegistryObject<Item> ORANGE_900_LAMP = block(RainbowLampModBlocks.ORANGE_900_LAMP);
	public static final RegistryObject<Item> PINK_50_LAMP = block(RainbowLampModBlocks.PINK_50_LAMP);
	public static final RegistryObject<Item> PINK_100_LAMP = block(RainbowLampModBlocks.PINK_100_LAMP);
	public static final RegistryObject<Item> PINK_200_LAMP = block(RainbowLampModBlocks.PINK_200_LAMP);
	public static final RegistryObject<Item> PINK_300_LAMP = block(RainbowLampModBlocks.PINK_300_LAMP);
	public static final RegistryObject<Item> PINK_400_LAMP = block(RainbowLampModBlocks.PINK_400_LAMP);
	public static final RegistryObject<Item> PINK_500_LAMP = block(RainbowLampModBlocks.PINK_500_LAMP);
	public static final RegistryObject<Item> PINK_600_LAMP = block(RainbowLampModBlocks.PINK_600_LAMP);
	public static final RegistryObject<Item> PINK_700_LAMP = block(RainbowLampModBlocks.PINK_700_LAMP);
	public static final RegistryObject<Item> PINK_800_LAMP = block(RainbowLampModBlocks.PINK_800_LAMP);
	public static final RegistryObject<Item> PINK_900_LAMP = block(RainbowLampModBlocks.PINK_900_LAMP);
	public static final RegistryObject<Item> PURPLE_50_LAMP = block(RainbowLampModBlocks.PURPLE_50_LAMP);
	public static final RegistryObject<Item> PURPLE_100_LAMP = block(RainbowLampModBlocks.PURPLE_100_LAMP);
	public static final RegistryObject<Item> PURPLE_200_LAMP = block(RainbowLampModBlocks.PURPLE_200_LAMP);
	public static final RegistryObject<Item> PURPLE_300_LAMP = block(RainbowLampModBlocks.PURPLE_300_LAMP);
	public static final RegistryObject<Item> PURPLE_400_LAMP = block(RainbowLampModBlocks.PURPLE_400_LAMP);
	public static final RegistryObject<Item> PURPLE_500_LAMP = block(RainbowLampModBlocks.PURPLE_500_LAMP);
	public static final RegistryObject<Item> PURPLE_600_LAMP = block(RainbowLampModBlocks.PURPLE_600_LAMP);
	public static final RegistryObject<Item> PURPLE_700_LAMP = block(RainbowLampModBlocks.PURPLE_700_LAMP);
	public static final RegistryObject<Item> PURPLE_800_LAMP = block(RainbowLampModBlocks.PURPLE_800_LAMP);
	public static final RegistryObject<Item> PURPLE_900_LAMP = block(RainbowLampModBlocks.PURPLE_900_LAMP);
	public static final RegistryObject<Item> RED_50_LAMP = block(RainbowLampModBlocks.RED_50_LAMP);
	public static final RegistryObject<Item> RED_100_LAMP = block(RainbowLampModBlocks.RED_100_LAMP);
	public static final RegistryObject<Item> RED_200_LAMP = block(RainbowLampModBlocks.RED_200_LAMP);
	public static final RegistryObject<Item> RED_300_LAMP = block(RainbowLampModBlocks.RED_300_LAMP);
	public static final RegistryObject<Item> RED_400_LAMP = block(RainbowLampModBlocks.RED_400_LAMP);
	public static final RegistryObject<Item> RED_500_LAMP = block(RainbowLampModBlocks.RED_500_LAMP);
	public static final RegistryObject<Item> RED_600_LAMP = block(RainbowLampModBlocks.RED_600_LAMP);
	public static final RegistryObject<Item> RED_700_LAMP = block(RainbowLampModBlocks.RED_700_LAMP);
	public static final RegistryObject<Item> RED_800_LAMP = block(RainbowLampModBlocks.RED_800_LAMP);
	public static final RegistryObject<Item> RED_900_LAMP = block(RainbowLampModBlocks.RED_900_LAMP);
	public static final RegistryObject<Item> YELLOW_50_LAMP = block(RainbowLampModBlocks.YELLOW_50_LAMP);
	public static final RegistryObject<Item> YELLOW_100_LAMP = block(RainbowLampModBlocks.YELLOW_100_LAMP);
	public static final RegistryObject<Item> YELLOW_200_LAMP = block(RainbowLampModBlocks.YELLOW_200_LAMP);
	public static final RegistryObject<Item> YELLOW_300_LAMP = block(RainbowLampModBlocks.YELLOW_300_LAMP);
	public static final RegistryObject<Item> YELLOW_400_LAMP = block(RainbowLampModBlocks.YELLOW_400_LAMP);
	public static final RegistryObject<Item> YELLOW_500_LAMP = block(RainbowLampModBlocks.YELLOW_500_LAMP);
	public static final RegistryObject<Item> YELLOW_600_LAMP = block(RainbowLampModBlocks.YELLOW_600_LAMP);
	public static final RegistryObject<Item> YELLOW_700_LAMP = block(RainbowLampModBlocks.YELLOW_700_LAMP);
	public static final RegistryObject<Item> YELLOW_800_LAMP = block(RainbowLampModBlocks.YELLOW_800_LAMP);
	public static final RegistryObject<Item> YELLOW_900_LAMP = block(RainbowLampModBlocks.YELLOW_900_LAMP);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
