
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package rainbow_glass.init;

import rainbow_glass.RainbowGlassMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class RainbowGlassModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, RainbowGlassMod.MODID);
	public static final RegistryObject<Item> BLUE_100_GLASS = block(RainbowGlassModBlocks.BLUE_100_GLASS);
	public static final RegistryObject<Item> BLUE_50_GLASS = block(RainbowGlassModBlocks.BLUE_50_GLASS);
	public static final RegistryObject<Item> BLUE_200_GLASS = block(RainbowGlassModBlocks.BLUE_200_GLASS);
	public static final RegistryObject<Item> BLUE_300_GLASS = block(RainbowGlassModBlocks.BLUE_300_GLASS);
	public static final RegistryObject<Item> BLUE_400_GLASS = block(RainbowGlassModBlocks.BLUE_400_GLASS);
	public static final RegistryObject<Item> BLUE_500_GLASS = block(RainbowGlassModBlocks.BLUE_500_GLASS);
	public static final RegistryObject<Item> BLUE_600_GLASS = block(RainbowGlassModBlocks.BLUE_600_GLASS);
	public static final RegistryObject<Item> BLUE_700_GLASS = block(RainbowGlassModBlocks.BLUE_700_GLASS);
	public static final RegistryObject<Item> BLUE_800_GLASS = block(RainbowGlassModBlocks.BLUE_800_GLASS);
	public static final RegistryObject<Item> BLUE_900_GLASS = block(RainbowGlassModBlocks.BLUE_900_GLASS);
	public static final RegistryObject<Item> BROWN_50_GLASS = block(RainbowGlassModBlocks.BROWN_50_GLASS);
	public static final RegistryObject<Item> BROWN_100_GLASS = block(RainbowGlassModBlocks.BROWN_100_GLASS);
	public static final RegistryObject<Item> BROWN_200_GLASS = block(RainbowGlassModBlocks.BROWN_200_GLASS);
	public static final RegistryObject<Item> BROWN_300_GLASS = block(RainbowGlassModBlocks.BROWN_300_GLASS);
	public static final RegistryObject<Item> BROWN_400_GLASS = block(RainbowGlassModBlocks.BROWN_400_GLASS);
	public static final RegistryObject<Item> BROWN_500_GLASS = block(RainbowGlassModBlocks.BROWN_500_GLASS);
	public static final RegistryObject<Item> BROWN_600_GLASS = block(RainbowGlassModBlocks.BROWN_600_GLASS);
	public static final RegistryObject<Item> BROWN_700_GLASS = block(RainbowGlassModBlocks.BROWN_700_GLASS);
	public static final RegistryObject<Item> BROWN_800_GLASS = block(RainbowGlassModBlocks.BROWN_800_GLASS);
	public static final RegistryObject<Item> BROWN_900_GLASS = block(RainbowGlassModBlocks.BROWN_900_GLASS);
	public static final RegistryObject<Item> CYAN_50_GLASS = block(RainbowGlassModBlocks.CYAN_50_GLASS);
	public static final RegistryObject<Item> CYAN_100_GLASS = block(RainbowGlassModBlocks.CYAN_100_GLASS);
	public static final RegistryObject<Item> CYAN_200_GLASS = block(RainbowGlassModBlocks.CYAN_200_GLASS);
	public static final RegistryObject<Item> CYAN_300_GLASS = block(RainbowGlassModBlocks.CYAN_300_GLASS);
	public static final RegistryObject<Item> CYAN_400_GLASS = block(RainbowGlassModBlocks.CYAN_400_GLASS);
	public static final RegistryObject<Item> CYAN_500_GLASS = block(RainbowGlassModBlocks.CYAN_500_GLASS);
	public static final RegistryObject<Item> CYAN_600_GLASS = block(RainbowGlassModBlocks.CYAN_600_GLASS);
	public static final RegistryObject<Item> CYAN_700_GLASS = block(RainbowGlassModBlocks.CYAN_700_GLASS);
	public static final RegistryObject<Item> CYAN_800_GLASS = block(RainbowGlassModBlocks.CYAN_800_GLASS);
	public static final RegistryObject<Item> CYAN_900_GLASS = block(RainbowGlassModBlocks.CYAN_900_GLASS);
	public static final RegistryObject<Item> GRAY_50_GLASS = block(RainbowGlassModBlocks.GRAY_50_GLASS);
	public static final RegistryObject<Item> GRAY_100_GLASS = block(RainbowGlassModBlocks.GRAY_100_GLASS);
	public static final RegistryObject<Item> GRAY_200_GLASS = block(RainbowGlassModBlocks.GRAY_200_GLASS);
	public static final RegistryObject<Item> GRAY_300_GLASS = block(RainbowGlassModBlocks.GRAY_300_GLASS);
	public static final RegistryObject<Item> GRAY_400_GLASS = block(RainbowGlassModBlocks.GRAY_400_GLASS);
	public static final RegistryObject<Item> GRAY_500_GLASS = block(RainbowGlassModBlocks.GRAY_500_GLASS);
	public static final RegistryObject<Item> GRAY_600_GLASS = block(RainbowGlassModBlocks.GRAY_600_GLASS);
	public static final RegistryObject<Item> GRAY_700_GLASS = block(RainbowGlassModBlocks.GRAY_700_GLASS);
	public static final RegistryObject<Item> GRAY_800_GLASS = block(RainbowGlassModBlocks.GRAY_800_GLASS);
	public static final RegistryObject<Item> GRAY_900_GLASS = block(RainbowGlassModBlocks.GRAY_900_GLASS);
	public static final RegistryObject<Item> GREEN_50_GLASS = block(RainbowGlassModBlocks.GREEN_50_GLASS);
	public static final RegistryObject<Item> GREEN_100_GLASS = block(RainbowGlassModBlocks.GREEN_100_GLASS);
	public static final RegistryObject<Item> GREEN_200_GLASS = block(RainbowGlassModBlocks.GREEN_200_GLASS);
	public static final RegistryObject<Item> GREEN_300_GLASS = block(RainbowGlassModBlocks.GREEN_300_GLASS);
	public static final RegistryObject<Item> GREEN_400_GLASS = block(RainbowGlassModBlocks.GREEN_400_GLASS);
	public static final RegistryObject<Item> GREEN_500_GLASS = block(RainbowGlassModBlocks.GREEN_500_GLASS);
	public static final RegistryObject<Item> GREEN_600_GLASS = block(RainbowGlassModBlocks.GREEN_600_GLASS);
	public static final RegistryObject<Item> GREEN_700_GLASS = block(RainbowGlassModBlocks.GREEN_700_GLASS);
	public static final RegistryObject<Item> GREEN_800_GLASS = block(RainbowGlassModBlocks.GREEN_800_GLASS);
	public static final RegistryObject<Item> GREEN_900_GLASS = block(RainbowGlassModBlocks.GREEN_900_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_50_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_50_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_100_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_100_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_200_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_200_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_300_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_300_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_400_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_400_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_500_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_500_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_600_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_600_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_700_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_700_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_800_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_800_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_900_GLASS = block(RainbowGlassModBlocks.LIGHT_BLUE_900_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_50_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_50_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_100_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_100_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_200_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_200_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_300_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_300_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_400_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_400_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_500_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_500_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_600_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_600_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_700_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_700_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_800_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_800_GLASS);
	public static final RegistryObject<Item> LIGHT_GRAY_900_GLASS = block(RainbowGlassModBlocks.LIGHT_GRAY_900_GLASS);
	public static final RegistryObject<Item> LIME_50_GLASS = block(RainbowGlassModBlocks.LIME_50_GLASS);
	public static final RegistryObject<Item> LIME_100_GLASS = block(RainbowGlassModBlocks.LIME_100_GLASS);
	public static final RegistryObject<Item> LIME_200_GLASS = block(RainbowGlassModBlocks.LIME_200_GLASS);
	public static final RegistryObject<Item> LIME_300_GLASS = block(RainbowGlassModBlocks.LIME_300_GLASS);
	public static final RegistryObject<Item> LIME_400_GLASS = block(RainbowGlassModBlocks.LIME_400_GLASS);
	public static final RegistryObject<Item> LIME_500_GLASS = block(RainbowGlassModBlocks.LIME_500_GLASS);
	public static final RegistryObject<Item> LIME_600_GLASS = block(RainbowGlassModBlocks.LIME_600_GLASS);
	public static final RegistryObject<Item> LIME_700_GLASS = block(RainbowGlassModBlocks.LIME_700_GLASS);
	public static final RegistryObject<Item> LIME_800_GLASS = block(RainbowGlassModBlocks.LIME_800_GLASS);
	public static final RegistryObject<Item> LIME_900_GLASS = block(RainbowGlassModBlocks.LIME_900_GLASS);
	public static final RegistryObject<Item> MAGENTA_50_GLASS = block(RainbowGlassModBlocks.MAGENTA_50_GLASS);
	public static final RegistryObject<Item> MAGENTA_100_GLASS = block(RainbowGlassModBlocks.MAGENTA_100_GLASS);
	public static final RegistryObject<Item> MAGENTA_200_GLASS = block(RainbowGlassModBlocks.MAGENTA_200_GLASS);
	public static final RegistryObject<Item> MAGENTA_300_GLASS = block(RainbowGlassModBlocks.MAGENTA_300_GLASS);
	public static final RegistryObject<Item> MAGENTA_400_GLASS = block(RainbowGlassModBlocks.MAGENTA_400_GLASS);
	public static final RegistryObject<Item> MAGENTA_500_GLASS = block(RainbowGlassModBlocks.MAGENTA_500_GLASS);
	public static final RegistryObject<Item> MAGENTA_600_GLASS = block(RainbowGlassModBlocks.MAGENTA_600_GLASS);
	public static final RegistryObject<Item> MAGENTA_700_GLASS = block(RainbowGlassModBlocks.MAGENTA_700_GLASS);
	public static final RegistryObject<Item> MAGENTA_800_GLASS = block(RainbowGlassModBlocks.MAGENTA_800_GLASS);
	public static final RegistryObject<Item> MAGENTA_900_GLASS = block(RainbowGlassModBlocks.MAGENTA_900_GLASS);
	public static final RegistryObject<Item> ORANGE_50_GLASS = block(RainbowGlassModBlocks.ORANGE_50_GLASS);
	public static final RegistryObject<Item> ORANGE_100_GLASS = block(RainbowGlassModBlocks.ORANGE_100_GLASS);
	public static final RegistryObject<Item> ORANGE_200_GLASS = block(RainbowGlassModBlocks.ORANGE_200_GLASS);
	public static final RegistryObject<Item> ORANGE_300_GLASS = block(RainbowGlassModBlocks.ORANGE_300_GLASS);
	public static final RegistryObject<Item> ORANGE_400_GLASS = block(RainbowGlassModBlocks.ORANGE_400_GLASS);
	public static final RegistryObject<Item> ORANGE_500_GLASS = block(RainbowGlassModBlocks.ORANGE_500_GLASS);
	public static final RegistryObject<Item> ORANGE_600_GLASS = block(RainbowGlassModBlocks.ORANGE_600_GLASS);
	public static final RegistryObject<Item> ORANGE_700_GLASS = block(RainbowGlassModBlocks.ORANGE_700_GLASS);
	public static final RegistryObject<Item> ORANGE_800_GLASS = block(RainbowGlassModBlocks.ORANGE_800_GLASS);
	public static final RegistryObject<Item> ORANGE_900_GLASS = block(RainbowGlassModBlocks.ORANGE_900_GLASS);
	public static final RegistryObject<Item> PINK_50_GLASS = block(RainbowGlassModBlocks.PINK_50_GLASS);
	public static final RegistryObject<Item> PINK_100_GLASS = block(RainbowGlassModBlocks.PINK_100_GLASS);
	public static final RegistryObject<Item> PINK_200_GLASS = block(RainbowGlassModBlocks.PINK_200_GLASS);
	public static final RegistryObject<Item> PINK_300_GLASS = block(RainbowGlassModBlocks.PINK_300_GLASS);
	public static final RegistryObject<Item> PINK_400_GLASS = block(RainbowGlassModBlocks.PINK_400_GLASS);
	public static final RegistryObject<Item> PINK_500_GLASS = block(RainbowGlassModBlocks.PINK_500_GLASS);
	public static final RegistryObject<Item> PINK_600_GLASS = block(RainbowGlassModBlocks.PINK_600_GLASS);
	public static final RegistryObject<Item> PINK_700_GLASS = block(RainbowGlassModBlocks.PINK_700_GLASS);
	public static final RegistryObject<Item> PINK_800_GLASS = block(RainbowGlassModBlocks.PINK_800_GLASS);
	public static final RegistryObject<Item> PINK_900_GLASS = block(RainbowGlassModBlocks.PINK_900_GLASS);
	public static final RegistryObject<Item> PURPLE_50_GLASS = block(RainbowGlassModBlocks.PURPLE_50_GLASS);
	public static final RegistryObject<Item> PURPLE_100_GLASS = block(RainbowGlassModBlocks.PURPLE_100_GLASS);
	public static final RegistryObject<Item> PURPLE_200_GLASS = block(RainbowGlassModBlocks.PURPLE_200_GLASS);
	public static final RegistryObject<Item> PURPLE_300_GLASS = block(RainbowGlassModBlocks.PURPLE_300_GLASS);
	public static final RegistryObject<Item> PURPLE_400_GLASS = block(RainbowGlassModBlocks.PURPLE_400_GLASS);
	public static final RegistryObject<Item> PURPLE_500_GLASS = block(RainbowGlassModBlocks.PURPLE_500_GLASS);
	public static final RegistryObject<Item> PURPLE_600_GLASS = block(RainbowGlassModBlocks.PURPLE_600_GLASS);
	public static final RegistryObject<Item> PURPLE_700_GLASS = block(RainbowGlassModBlocks.PURPLE_700_GLASS);
	public static final RegistryObject<Item> PURPLE_800_GLASS = block(RainbowGlassModBlocks.PURPLE_800_GLASS);
	public static final RegistryObject<Item> PURPLE_900_GLASS = block(RainbowGlassModBlocks.PURPLE_900_GLASS);
	public static final RegistryObject<Item> RED_50_GLASS = block(RainbowGlassModBlocks.RED_50_GLASS);
	public static final RegistryObject<Item> RED_100_GLASS = block(RainbowGlassModBlocks.RED_100_GLASS);
	public static final RegistryObject<Item> RED_200_GLASS = block(RainbowGlassModBlocks.RED_200_GLASS);
	public static final RegistryObject<Item> RED_300_GLASS = block(RainbowGlassModBlocks.RED_300_GLASS);
	public static final RegistryObject<Item> RED_400_GLASS = block(RainbowGlassModBlocks.RED_400_GLASS);
	public static final RegistryObject<Item> RED_500_GLASS = block(RainbowGlassModBlocks.RED_500_GLASS);
	public static final RegistryObject<Item> RED_600_GLASS = block(RainbowGlassModBlocks.RED_600_GLASS);
	public static final RegistryObject<Item> RED_700_GLASS = block(RainbowGlassModBlocks.RED_700_GLASS);
	public static final RegistryObject<Item> RED_800_GLASS = block(RainbowGlassModBlocks.RED_800_GLASS);
	public static final RegistryObject<Item> RED_900_GLASS = block(RainbowGlassModBlocks.RED_900_GLASS);
	public static final RegistryObject<Item> YELLOW_50_GLASS = block(RainbowGlassModBlocks.YELLOW_50_GLASS);
	public static final RegistryObject<Item> YELLOW_100_GLASS = block(RainbowGlassModBlocks.YELLOW_100_GLASS);
	public static final RegistryObject<Item> YELLOW_200_GLASS = block(RainbowGlassModBlocks.YELLOW_200_GLASS);
	public static final RegistryObject<Item> YELLOW_300_GLASS = block(RainbowGlassModBlocks.YELLOW_300_GLASS);
	public static final RegistryObject<Item> YELLOW_400_GLASS = block(RainbowGlassModBlocks.YELLOW_400_GLASS);
	public static final RegistryObject<Item> YELLOW_500_GLASS = block(RainbowGlassModBlocks.YELLOW_500_GLASS);
	public static final RegistryObject<Item> YELLOW_600_GLASS = block(RainbowGlassModBlocks.YELLOW_600_GLASS);
	public static final RegistryObject<Item> YELLOW_700_GLASS = block(RainbowGlassModBlocks.YELLOW_700_GLASS);
	public static final RegistryObject<Item> YELLOW_800_GLASS = block(RainbowGlassModBlocks.YELLOW_800_GLASS);
	public static final RegistryObject<Item> YELLOW_900_GLASS = block(RainbowGlassModBlocks.YELLOW_900_GLASS);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
