
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package rainbow_glass.init;

import rainbow_glass.block.Yellow900GlassBlock;
import rainbow_glass.block.Yellow800GlassBlock;
import rainbow_glass.block.Yellow700GlassBlock;
import rainbow_glass.block.Yellow600GlassBlock;
import rainbow_glass.block.Yellow50GlassBlock;
import rainbow_glass.block.Yellow500GlassBlock;
import rainbow_glass.block.Yellow400GlassBlock;
import rainbow_glass.block.Yellow300GlassBlock;
import rainbow_glass.block.Yellow200GlassBlock;
import rainbow_glass.block.Yellow100GlassBlock;
import rainbow_glass.block.Red900GlassBlock;
import rainbow_glass.block.Red800GlassBlock;
import rainbow_glass.block.Red700GlassBlock;
import rainbow_glass.block.Red600GlassBlock;
import rainbow_glass.block.Red50GlassBlock;
import rainbow_glass.block.Red500GlassBlock;
import rainbow_glass.block.Red400GlassBlock;
import rainbow_glass.block.Red300GlassBlock;
import rainbow_glass.block.Red200GlassBlock;
import rainbow_glass.block.Red100GlassBlock;
import rainbow_glass.block.Purple900GlassBlock;
import rainbow_glass.block.Purple800GlassBlock;
import rainbow_glass.block.Purple700GlassBlock;
import rainbow_glass.block.Purple600GlassBlock;
import rainbow_glass.block.Purple50GlassBlock;
import rainbow_glass.block.Purple500GlassBlock;
import rainbow_glass.block.Purple400GlassBlock;
import rainbow_glass.block.Purple300GlassBlock;
import rainbow_glass.block.Purple200GlassBlock;
import rainbow_glass.block.Purple100GlassBlock;
import rainbow_glass.block.Pink900GlassBlock;
import rainbow_glass.block.Pink800GlassBlock;
import rainbow_glass.block.Pink700GlassBlock;
import rainbow_glass.block.Pink600GlassBlock;
import rainbow_glass.block.Pink50GlassBlock;
import rainbow_glass.block.Pink500GlassBlock;
import rainbow_glass.block.Pink400GlassBlock;
import rainbow_glass.block.Pink300GlassBlock;
import rainbow_glass.block.Pink200GlassBlock;
import rainbow_glass.block.Pink100GlassBlock;
import rainbow_glass.block.Orange900GlassBlock;
import rainbow_glass.block.Orange800GlassBlock;
import rainbow_glass.block.Orange700GlassBlock;
import rainbow_glass.block.Orange600GlassBlock;
import rainbow_glass.block.Orange50GlassBlock;
import rainbow_glass.block.Orange500GlassBlock;
import rainbow_glass.block.Orange400GlassBlock;
import rainbow_glass.block.Orange300GlassBlock;
import rainbow_glass.block.Orange200GlassBlock;
import rainbow_glass.block.Orange100GlassBlock;
import rainbow_glass.block.Magenta900GlassBlock;
import rainbow_glass.block.Magenta800GlassBlock;
import rainbow_glass.block.Magenta700GlassBlock;
import rainbow_glass.block.Magenta600GlassBlock;
import rainbow_glass.block.Magenta50GlassBlock;
import rainbow_glass.block.Magenta500GlassBlock;
import rainbow_glass.block.Magenta400GlassBlock;
import rainbow_glass.block.Magenta300GlassBlock;
import rainbow_glass.block.Magenta200GlassBlock;
import rainbow_glass.block.Magenta100GlassBlock;
import rainbow_glass.block.Lime900GlassBlock;
import rainbow_glass.block.Lime800GlassBlock;
import rainbow_glass.block.Lime700GlassBlock;
import rainbow_glass.block.Lime600GlassBlock;
import rainbow_glass.block.Lime50GlassBlock;
import rainbow_glass.block.Lime500GlassBlock;
import rainbow_glass.block.Lime400GlassBlock;
import rainbow_glass.block.Lime300GlassBlock;
import rainbow_glass.block.Lime200GlassBlock;
import rainbow_glass.block.Lime100GlassBlock;
import rainbow_glass.block.LightGray900GlassBlock;
import rainbow_glass.block.LightGray800GlassBlock;
import rainbow_glass.block.LightGray700GlassBlock;
import rainbow_glass.block.LightGray600GlassBlock;
import rainbow_glass.block.LightGray50GlassBlock;
import rainbow_glass.block.LightGray500GlassBlock;
import rainbow_glass.block.LightGray400GlassBlock;
import rainbow_glass.block.LightGray300GlassBlock;
import rainbow_glass.block.LightGray200GlassBlock;
import rainbow_glass.block.LightGray100GlassBlock;
import rainbow_glass.block.LightBlue900GlassBlock;
import rainbow_glass.block.LightBlue800GlassBlock;
import rainbow_glass.block.LightBlue700GlassBlock;
import rainbow_glass.block.LightBlue600GlassBlock;
import rainbow_glass.block.LightBlue50GlassBlock;
import rainbow_glass.block.LightBlue500GlassBlock;
import rainbow_glass.block.LightBlue400GlassBlock;
import rainbow_glass.block.LightBlue300GlassBlock;
import rainbow_glass.block.LightBlue200GlassBlock;
import rainbow_glass.block.LightBlue100GlassBlock;
import rainbow_glass.block.Green900GlassBlock;
import rainbow_glass.block.Green800GlassBlock;
import rainbow_glass.block.Green700GlassBlock;
import rainbow_glass.block.Green600GlassBlock;
import rainbow_glass.block.Green50GlassBlock;
import rainbow_glass.block.Green500GlassBlock;
import rainbow_glass.block.Green400GlassBlock;
import rainbow_glass.block.Green300GlassBlock;
import rainbow_glass.block.Green200GlassBlock;
import rainbow_glass.block.Green100GlassBlock;
import rainbow_glass.block.Gray900GlassBlock;
import rainbow_glass.block.Gray800GlassBlock;
import rainbow_glass.block.Gray700GlassBlock;
import rainbow_glass.block.Gray600GlassBlock;
import rainbow_glass.block.Gray50GlassBlock;
import rainbow_glass.block.Gray500GlassBlock;
import rainbow_glass.block.Gray400GlassBlock;
import rainbow_glass.block.Gray300GlassBlock;
import rainbow_glass.block.Gray200GlassBlock;
import rainbow_glass.block.Gray100GlassBlock;
import rainbow_glass.block.Cyan900GlassBlock;
import rainbow_glass.block.Cyan800GlassBlock;
import rainbow_glass.block.Cyan700GlassBlock;
import rainbow_glass.block.Cyan600GlassBlock;
import rainbow_glass.block.Cyan50GlassBlock;
import rainbow_glass.block.Cyan500GlassBlock;
import rainbow_glass.block.Cyan400GlassBlock;
import rainbow_glass.block.Cyan300GlassBlock;
import rainbow_glass.block.Cyan200GlassBlock;
import rainbow_glass.block.Cyan100GlassBlock;
import rainbow_glass.block.Brown900GlassBlock;
import rainbow_glass.block.Brown800GlassBlock;
import rainbow_glass.block.Brown700GlassBlock;
import rainbow_glass.block.Brown600GlassBlock;
import rainbow_glass.block.Brown50GlassBlock;
import rainbow_glass.block.Brown500GlassBlock;
import rainbow_glass.block.Brown400GlassBlock;
import rainbow_glass.block.Brown300GlassBlock;
import rainbow_glass.block.Brown200GlassBlock;
import rainbow_glass.block.Brown100GlassBlock;
import rainbow_glass.block.Blue900GlassBlock;
import rainbow_glass.block.Blue800GlassBlock;
import rainbow_glass.block.Blue700GlassBlock;
import rainbow_glass.block.Blue600GlassBlock;
import rainbow_glass.block.Blue50GlassBlock;
import rainbow_glass.block.Blue500GlassBlock;
import rainbow_glass.block.Blue400GlassBlock;
import rainbow_glass.block.Blue300GlassBlock;
import rainbow_glass.block.Blue200GlassBlock;
import rainbow_glass.block.Blue100GlassBlock;

import rainbow_glass.RainbowGlassMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class RainbowGlassModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, RainbowGlassMod.MODID);
	public static final RegistryObject<Block> BLUE_100_GLASS = REGISTRY.register("blue_100_glass", () -> new Blue100GlassBlock());
	public static final RegistryObject<Block> BLUE_50_GLASS = REGISTRY.register("blue_50_glass", () -> new Blue50GlassBlock());
	public static final RegistryObject<Block> BLUE_200_GLASS = REGISTRY.register("blue_200_glass", () -> new Blue200GlassBlock());
	public static final RegistryObject<Block> BLUE_300_GLASS = REGISTRY.register("blue_300_glass", () -> new Blue300GlassBlock());
	public static final RegistryObject<Block> BLUE_400_GLASS = REGISTRY.register("blue_400_glass", () -> new Blue400GlassBlock());
	public static final RegistryObject<Block> BLUE_500_GLASS = REGISTRY.register("blue_500_glass", () -> new Blue500GlassBlock());
	public static final RegistryObject<Block> BLUE_600_GLASS = REGISTRY.register("blue_600_glass", () -> new Blue600GlassBlock());
	public static final RegistryObject<Block> BLUE_700_GLASS = REGISTRY.register("blue_700_glass", () -> new Blue700GlassBlock());
	public static final RegistryObject<Block> BLUE_800_GLASS = REGISTRY.register("blue_800_glass", () -> new Blue800GlassBlock());
	public static final RegistryObject<Block> BLUE_900_GLASS = REGISTRY.register("blue_900_glass", () -> new Blue900GlassBlock());
	public static final RegistryObject<Block> BROWN_50_GLASS = REGISTRY.register("brown_50_glass", () -> new Brown50GlassBlock());
	public static final RegistryObject<Block> BROWN_100_GLASS = REGISTRY.register("brown_100_glass", () -> new Brown100GlassBlock());
	public static final RegistryObject<Block> BROWN_200_GLASS = REGISTRY.register("brown_200_glass", () -> new Brown200GlassBlock());
	public static final RegistryObject<Block> BROWN_300_GLASS = REGISTRY.register("brown_300_glass", () -> new Brown300GlassBlock());
	public static final RegistryObject<Block> BROWN_400_GLASS = REGISTRY.register("brown_400_glass", () -> new Brown400GlassBlock());
	public static final RegistryObject<Block> BROWN_500_GLASS = REGISTRY.register("brown_500_glass", () -> new Brown500GlassBlock());
	public static final RegistryObject<Block> BROWN_600_GLASS = REGISTRY.register("brown_600_glass", () -> new Brown600GlassBlock());
	public static final RegistryObject<Block> BROWN_700_GLASS = REGISTRY.register("brown_700_glass", () -> new Brown700GlassBlock());
	public static final RegistryObject<Block> BROWN_800_GLASS = REGISTRY.register("brown_800_glass", () -> new Brown800GlassBlock());
	public static final RegistryObject<Block> BROWN_900_GLASS = REGISTRY.register("brown_900_glass", () -> new Brown900GlassBlock());
	public static final RegistryObject<Block> CYAN_50_GLASS = REGISTRY.register("cyan_50_glass", () -> new Cyan50GlassBlock());
	public static final RegistryObject<Block> CYAN_100_GLASS = REGISTRY.register("cyan_100_glass", () -> new Cyan100GlassBlock());
	public static final RegistryObject<Block> CYAN_200_GLASS = REGISTRY.register("cyan_200_glass", () -> new Cyan200GlassBlock());
	public static final RegistryObject<Block> CYAN_300_GLASS = REGISTRY.register("cyan_300_glass", () -> new Cyan300GlassBlock());
	public static final RegistryObject<Block> CYAN_400_GLASS = REGISTRY.register("cyan_400_glass", () -> new Cyan400GlassBlock());
	public static final RegistryObject<Block> CYAN_500_GLASS = REGISTRY.register("cyan_500_glass", () -> new Cyan500GlassBlock());
	public static final RegistryObject<Block> CYAN_600_GLASS = REGISTRY.register("cyan_600_glass", () -> new Cyan600GlassBlock());
	public static final RegistryObject<Block> CYAN_700_GLASS = REGISTRY.register("cyan_700_glass", () -> new Cyan700GlassBlock());
	public static final RegistryObject<Block> CYAN_800_GLASS = REGISTRY.register("cyan_800_glass", () -> new Cyan800GlassBlock());
	public static final RegistryObject<Block> CYAN_900_GLASS = REGISTRY.register("cyan_900_glass", () -> new Cyan900GlassBlock());
	public static final RegistryObject<Block> GRAY_50_GLASS = REGISTRY.register("gray_50_glass", () -> new Gray50GlassBlock());
	public static final RegistryObject<Block> GRAY_100_GLASS = REGISTRY.register("gray_100_glass", () -> new Gray100GlassBlock());
	public static final RegistryObject<Block> GRAY_200_GLASS = REGISTRY.register("gray_200_glass", () -> new Gray200GlassBlock());
	public static final RegistryObject<Block> GRAY_300_GLASS = REGISTRY.register("gray_300_glass", () -> new Gray300GlassBlock());
	public static final RegistryObject<Block> GRAY_400_GLASS = REGISTRY.register("gray_400_glass", () -> new Gray400GlassBlock());
	public static final RegistryObject<Block> GRAY_500_GLASS = REGISTRY.register("gray_500_glass", () -> new Gray500GlassBlock());
	public static final RegistryObject<Block> GRAY_600_GLASS = REGISTRY.register("gray_600_glass", () -> new Gray600GlassBlock());
	public static final RegistryObject<Block> GRAY_700_GLASS = REGISTRY.register("gray_700_glass", () -> new Gray700GlassBlock());
	public static final RegistryObject<Block> GRAY_800_GLASS = REGISTRY.register("gray_800_glass", () -> new Gray800GlassBlock());
	public static final RegistryObject<Block> GRAY_900_GLASS = REGISTRY.register("gray_900_glass", () -> new Gray900GlassBlock());
	public static final RegistryObject<Block> GREEN_50_GLASS = REGISTRY.register("green_50_glass", () -> new Green50GlassBlock());
	public static final RegistryObject<Block> GREEN_100_GLASS = REGISTRY.register("green_100_glass", () -> new Green100GlassBlock());
	public static final RegistryObject<Block> GREEN_200_GLASS = REGISTRY.register("green_200_glass", () -> new Green200GlassBlock());
	public static final RegistryObject<Block> GREEN_300_GLASS = REGISTRY.register("green_300_glass", () -> new Green300GlassBlock());
	public static final RegistryObject<Block> GREEN_400_GLASS = REGISTRY.register("green_400_glass", () -> new Green400GlassBlock());
	public static final RegistryObject<Block> GREEN_500_GLASS = REGISTRY.register("green_500_glass", () -> new Green500GlassBlock());
	public static final RegistryObject<Block> GREEN_600_GLASS = REGISTRY.register("green_600_glass", () -> new Green600GlassBlock());
	public static final RegistryObject<Block> GREEN_700_GLASS = REGISTRY.register("green_700_glass", () -> new Green700GlassBlock());
	public static final RegistryObject<Block> GREEN_800_GLASS = REGISTRY.register("green_800_glass", () -> new Green800GlassBlock());
	public static final RegistryObject<Block> GREEN_900_GLASS = REGISTRY.register("green_900_glass", () -> new Green900GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_50_GLASS = REGISTRY.register("light_blue_50_glass", () -> new LightBlue50GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_100_GLASS = REGISTRY.register("light_blue_100_glass", () -> new LightBlue100GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_200_GLASS = REGISTRY.register("light_blue_200_glass", () -> new LightBlue200GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_300_GLASS = REGISTRY.register("light_blue_300_glass", () -> new LightBlue300GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_400_GLASS = REGISTRY.register("light_blue_400_glass", () -> new LightBlue400GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_500_GLASS = REGISTRY.register("light_blue_500_glass", () -> new LightBlue500GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_600_GLASS = REGISTRY.register("light_blue_600_glass", () -> new LightBlue600GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_700_GLASS = REGISTRY.register("light_blue_700_glass", () -> new LightBlue700GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_800_GLASS = REGISTRY.register("light_blue_800_glass", () -> new LightBlue800GlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_900_GLASS = REGISTRY.register("light_blue_900_glass", () -> new LightBlue900GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_50_GLASS = REGISTRY.register("light_gray_50_glass", () -> new LightGray50GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_100_GLASS = REGISTRY.register("light_gray_100_glass", () -> new LightGray100GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_200_GLASS = REGISTRY.register("light_gray_200_glass", () -> new LightGray200GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_300_GLASS = REGISTRY.register("light_gray_300_glass", () -> new LightGray300GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_400_GLASS = REGISTRY.register("light_gray_400_glass", () -> new LightGray400GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_500_GLASS = REGISTRY.register("light_gray_500_glass", () -> new LightGray500GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_600_GLASS = REGISTRY.register("light_gray_600_glass", () -> new LightGray600GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_700_GLASS = REGISTRY.register("light_gray_700_glass", () -> new LightGray700GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_800_GLASS = REGISTRY.register("light_gray_800_glass", () -> new LightGray800GlassBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_900_GLASS = REGISTRY.register("light_gray_900_glass", () -> new LightGray900GlassBlock());
	public static final RegistryObject<Block> LIME_50_GLASS = REGISTRY.register("lime_50_glass", () -> new Lime50GlassBlock());
	public static final RegistryObject<Block> LIME_100_GLASS = REGISTRY.register("lime_100_glass", () -> new Lime100GlassBlock());
	public static final RegistryObject<Block> LIME_200_GLASS = REGISTRY.register("lime_200_glass", () -> new Lime200GlassBlock());
	public static final RegistryObject<Block> LIME_300_GLASS = REGISTRY.register("lime_300_glass", () -> new Lime300GlassBlock());
	public static final RegistryObject<Block> LIME_400_GLASS = REGISTRY.register("lime_400_glass", () -> new Lime400GlassBlock());
	public static final RegistryObject<Block> LIME_500_GLASS = REGISTRY.register("lime_500_glass", () -> new Lime500GlassBlock());
	public static final RegistryObject<Block> LIME_600_GLASS = REGISTRY.register("lime_600_glass", () -> new Lime600GlassBlock());
	public static final RegistryObject<Block> LIME_700_GLASS = REGISTRY.register("lime_700_glass", () -> new Lime700GlassBlock());
	public static final RegistryObject<Block> LIME_800_GLASS = REGISTRY.register("lime_800_glass", () -> new Lime800GlassBlock());
	public static final RegistryObject<Block> LIME_900_GLASS = REGISTRY.register("lime_900_glass", () -> new Lime900GlassBlock());
	public static final RegistryObject<Block> MAGENTA_50_GLASS = REGISTRY.register("magenta_50_glass", () -> new Magenta50GlassBlock());
	public static final RegistryObject<Block> MAGENTA_100_GLASS = REGISTRY.register("magenta_100_glass", () -> new Magenta100GlassBlock());
	public static final RegistryObject<Block> MAGENTA_200_GLASS = REGISTRY.register("magenta_200_glass", () -> new Magenta200GlassBlock());
	public static final RegistryObject<Block> MAGENTA_300_GLASS = REGISTRY.register("magenta_300_glass", () -> new Magenta300GlassBlock());
	public static final RegistryObject<Block> MAGENTA_400_GLASS = REGISTRY.register("magenta_400_glass", () -> new Magenta400GlassBlock());
	public static final RegistryObject<Block> MAGENTA_500_GLASS = REGISTRY.register("magenta_500_glass", () -> new Magenta500GlassBlock());
	public static final RegistryObject<Block> MAGENTA_600_GLASS = REGISTRY.register("magenta_600_glass", () -> new Magenta600GlassBlock());
	public static final RegistryObject<Block> MAGENTA_700_GLASS = REGISTRY.register("magenta_700_glass", () -> new Magenta700GlassBlock());
	public static final RegistryObject<Block> MAGENTA_800_GLASS = REGISTRY.register("magenta_800_glass", () -> new Magenta800GlassBlock());
	public static final RegistryObject<Block> MAGENTA_900_GLASS = REGISTRY.register("magenta_900_glass", () -> new Magenta900GlassBlock());
	public static final RegistryObject<Block> ORANGE_50_GLASS = REGISTRY.register("orange_50_glass", () -> new Orange50GlassBlock());
	public static final RegistryObject<Block> ORANGE_100_GLASS = REGISTRY.register("orange_100_glass", () -> new Orange100GlassBlock());
	public static final RegistryObject<Block> ORANGE_200_GLASS = REGISTRY.register("orange_200_glass", () -> new Orange200GlassBlock());
	public static final RegistryObject<Block> ORANGE_300_GLASS = REGISTRY.register("orange_300_glass", () -> new Orange300GlassBlock());
	public static final RegistryObject<Block> ORANGE_400_GLASS = REGISTRY.register("orange_400_glass", () -> new Orange400GlassBlock());
	public static final RegistryObject<Block> ORANGE_500_GLASS = REGISTRY.register("orange_500_glass", () -> new Orange500GlassBlock());
	public static final RegistryObject<Block> ORANGE_600_GLASS = REGISTRY.register("orange_600_glass", () -> new Orange600GlassBlock());
	public static final RegistryObject<Block> ORANGE_700_GLASS = REGISTRY.register("orange_700_glass", () -> new Orange700GlassBlock());
	public static final RegistryObject<Block> ORANGE_800_GLASS = REGISTRY.register("orange_800_glass", () -> new Orange800GlassBlock());
	public static final RegistryObject<Block> ORANGE_900_GLASS = REGISTRY.register("orange_900_glass", () -> new Orange900GlassBlock());
	public static final RegistryObject<Block> PINK_50_GLASS = REGISTRY.register("pink_50_glass", () -> new Pink50GlassBlock());
	public static final RegistryObject<Block> PINK_100_GLASS = REGISTRY.register("pink_100_glass", () -> new Pink100GlassBlock());
	public static final RegistryObject<Block> PINK_200_GLASS = REGISTRY.register("pink_200_glass", () -> new Pink200GlassBlock());
	public static final RegistryObject<Block> PINK_300_GLASS = REGISTRY.register("pink_300_glass", () -> new Pink300GlassBlock());
	public static final RegistryObject<Block> PINK_400_GLASS = REGISTRY.register("pink_400_glass", () -> new Pink400GlassBlock());
	public static final RegistryObject<Block> PINK_500_GLASS = REGISTRY.register("pink_500_glass", () -> new Pink500GlassBlock());
	public static final RegistryObject<Block> PINK_600_GLASS = REGISTRY.register("pink_600_glass", () -> new Pink600GlassBlock());
	public static final RegistryObject<Block> PINK_700_GLASS = REGISTRY.register("pink_700_glass", () -> new Pink700GlassBlock());
	public static final RegistryObject<Block> PINK_800_GLASS = REGISTRY.register("pink_800_glass", () -> new Pink800GlassBlock());
	public static final RegistryObject<Block> PINK_900_GLASS = REGISTRY.register("pink_900_glass", () -> new Pink900GlassBlock());
	public static final RegistryObject<Block> PURPLE_50_GLASS = REGISTRY.register("purple_50_glass", () -> new Purple50GlassBlock());
	public static final RegistryObject<Block> PURPLE_100_GLASS = REGISTRY.register("purple_100_glass", () -> new Purple100GlassBlock());
	public static final RegistryObject<Block> PURPLE_200_GLASS = REGISTRY.register("purple_200_glass", () -> new Purple200GlassBlock());
	public static final RegistryObject<Block> PURPLE_300_GLASS = REGISTRY.register("purple_300_glass", () -> new Purple300GlassBlock());
	public static final RegistryObject<Block> PURPLE_400_GLASS = REGISTRY.register("purple_400_glass", () -> new Purple400GlassBlock());
	public static final RegistryObject<Block> PURPLE_500_GLASS = REGISTRY.register("purple_500_glass", () -> new Purple500GlassBlock());
	public static final RegistryObject<Block> PURPLE_600_GLASS = REGISTRY.register("purple_600_glass", () -> new Purple600GlassBlock());
	public static final RegistryObject<Block> PURPLE_700_GLASS = REGISTRY.register("purple_700_glass", () -> new Purple700GlassBlock());
	public static final RegistryObject<Block> PURPLE_800_GLASS = REGISTRY.register("purple_800_glass", () -> new Purple800GlassBlock());
	public static final RegistryObject<Block> PURPLE_900_GLASS = REGISTRY.register("purple_900_glass", () -> new Purple900GlassBlock());
	public static final RegistryObject<Block> RED_50_GLASS = REGISTRY.register("red_50_glass", () -> new Red50GlassBlock());
	public static final RegistryObject<Block> RED_100_GLASS = REGISTRY.register("red_100_glass", () -> new Red100GlassBlock());
	public static final RegistryObject<Block> RED_200_GLASS = REGISTRY.register("red_200_glass", () -> new Red200GlassBlock());
	public static final RegistryObject<Block> RED_300_GLASS = REGISTRY.register("red_300_glass", () -> new Red300GlassBlock());
	public static final RegistryObject<Block> RED_400_GLASS = REGISTRY.register("red_400_glass", () -> new Red400GlassBlock());
	public static final RegistryObject<Block> RED_500_GLASS = REGISTRY.register("red_500_glass", () -> new Red500GlassBlock());
	public static final RegistryObject<Block> RED_600_GLASS = REGISTRY.register("red_600_glass", () -> new Red600GlassBlock());
	public static final RegistryObject<Block> RED_700_GLASS = REGISTRY.register("red_700_glass", () -> new Red700GlassBlock());
	public static final RegistryObject<Block> RED_800_GLASS = REGISTRY.register("red_800_glass", () -> new Red800GlassBlock());
	public static final RegistryObject<Block> RED_900_GLASS = REGISTRY.register("red_900_glass", () -> new Red900GlassBlock());
	public static final RegistryObject<Block> YELLOW_50_GLASS = REGISTRY.register("yellow_50_glass", () -> new Yellow50GlassBlock());
	public static final RegistryObject<Block> YELLOW_100_GLASS = REGISTRY.register("yellow_100_glass", () -> new Yellow100GlassBlock());
	public static final RegistryObject<Block> YELLOW_200_GLASS = REGISTRY.register("yellow_200_glass", () -> new Yellow200GlassBlock());
	public static final RegistryObject<Block> YELLOW_300_GLASS = REGISTRY.register("yellow_300_glass", () -> new Yellow300GlassBlock());
	public static final RegistryObject<Block> YELLOW_400_GLASS = REGISTRY.register("yellow_400_glass", () -> new Yellow400GlassBlock());
	public static final RegistryObject<Block> YELLOW_500_GLASS = REGISTRY.register("yellow_500_glass", () -> new Yellow500GlassBlock());
	public static final RegistryObject<Block> YELLOW_600_GLASS = REGISTRY.register("yellow_600_glass", () -> new Yellow600GlassBlock());
	public static final RegistryObject<Block> YELLOW_700_GLASS = REGISTRY.register("yellow_700_glass", () -> new Yellow700GlassBlock());
	public static final RegistryObject<Block> YELLOW_800_GLASS = REGISTRY.register("yellow_800_glass", () -> new Yellow800GlassBlock());
	public static final RegistryObject<Block> YELLOW_900_GLASS = REGISTRY.register("yellow_900_glass", () -> new Yellow900GlassBlock());
}
