name: Deno Deploy
on:
  push:
    branches: [ deploy ]

  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Setup repo
      uses: actions/checkout@v2

    - name: Setup Deno
      # uses: denoland/setup-deno@v1
      uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
      with:
        deno-version: v1.x
    - name: Deploy to Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: minecraft-pixel-art
        entrypoint: src/app.ts
