name: Deno Deploy
on:
  push:
    branches: [ deploy ]

  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
      with:
        ref: deploy
    - name: Deploy to Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: "minecraft-pixel-art"
        import-map: "./import_map.json"
        entrypoint: "./src/app.ts"
